stotko/stdgpu

- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/iterator.h
The macro function `STDGPU_DETAIL_SAFE_CALL` is only used by the workarounds in `memory_detail.h`. Move the workarounds into dedicated functions to `memory.cpp`. This allows to move the macro `STDGPU_DETAIL_SAFE_CALL` as well to avoid exposing this internal detail to users.
> memory: Cleanup detail header

- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
The raw functions `atomicX` defined by the CUDA backend are used in `bitset` and `unordered_set`. Replace them by calls to `atomic_ref` to reduce the coupling to the CUDA backend.
> bitset,unordered_base: Use atomic_ref over raw function

- src/stdgpu/impl/unordered_base_detail.cuh
In certain circumstances, a kernel timeout may occur when calling the blocking `insert` and `erase` functions. Since the internal while loops run until the execution of the respective operation was successful (or stop if this is not possible), an infinite loop must not occur. Use a for loop with a sufficient range to workaround possible compiler/scheduler issues that may still lead to infinite loops.
> unordered_base: Workaround while loop timeouts

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
Several member functions of `deque`, `unordered_map`, `unordered_set`, and `vector` use the public typedefs in the function signatures. As they are dependent names, the `typename` keyword is required for disambiguation. Add it where it was previously missing to avoid compilation errors.
> deque,unordered_{map,set},vector: Fix missing typename

- test/stdgpu/atomic.cu
The unit test of `atomic` uses patterns with a single set bit to test the functionality. Use a cast during bit shifting to avoid truncation issues and potential test failures.
> atomic: Fix bit shift in unit test

- test/stdgpu/unordered_map.cu
- test/stdgpu/unordered_set.cu
The test data structures used for `unordered_map` and `unordered_set` were defined in an anonymous namespace. Remove it and mark `operator==` as inline.
> unordered_{map,set}: Remove unnecessary anonymous namespace

- test/stdgpu/deque.cu
- test/stdgpu/vector.cu
The unit tests of `deque` and vector` assume that the object state becomes invalid when pushing or popping too many elements. However, there is preemptive check that tries to avoid getting into this invalid state. Remove the check in the test as the object may remain in a valid state.
> deque,vector: Remove unreliable validity check in unit test

- test/stdgpu/mutex.cu
There was a typo (`bothl` --> `both`) in the name of a unit test. Fix this.
> mutex: Fix typo in test name

- src/stdgpu/impl/unordered_base_detail.cuh
If Fibonacci Hashing is used, the result of the bucket function may exceed the bucket count in case of a bucket count of 1. This is due to a bit shift by 64 that will be performed in this case which leads to undefined/unreliable behavior. Handle this corner case by explicitly returning the only possible bucket position, i.e. return 0 in this case. Furthermore, use `std::size_t` instead of `size_t` to improve the consistency.
> unordered_base: Fix corner case in bucket computation

- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/cuda/memory.h
- src/stdgpu/impl/memory.cpp
The function `get_dynamic_memory_type` is considered backend-specific as it contains plain CUDA function calls. Use our internal memory management system to implement a generic version. This reduces the requirements and will ease the implementation future backends.
> memory: Reduce requirements to backend

- test/stdgpu/cuda/CMakeLists.txt
- test/stdgpu/cuda/device_info.cpp
- test/stdgpu/cuda/device_info.h
- test/stdgpu/main.cpp
The device information part of the test main file still contains plain CUDA code. Factor this into a dedicated file to better separate generic from backend-specific code.
> test: Split backend-specific device information code into dedicated file

- src/stdgpu/impl/unordered_base_detail.cuh
In case of inserting the same value multiple times in parallel (see unit test), this operation may be performed more than once which leads to duplicates within the container. Although the actual insertion process is already properly guarded by a lock and double-check mechanism, speculation and cache issues due to operation reordering may occur and make a thread believe that the value is not yet inserted (value and link set, but occupancy status still unset). Workaround this by updating the link to the newly created values after its occupancy status has been set.
Furthermore, revert the loop timeout workaround (#3) and replace it back to a while loop.
> unordered_base: Improve reliability

- src/stdgpu/impl/memory_detail.h
- test/stdgpu/memory.inc
thrust uses an optimization within the `uninitialized_fill` function in case the type `T` has a trivial copy constructor. However, as they actually perform copy assignment rather than copy construction, this may cause compilation failures for types `T` that have a copy constructor but no copy assignment operator. Since the detection code for this mechanism also differs for different compilers, the behavior is rather unpredictable. Define an own internal version of `uninitialized_fill` to workaround this issue.
> memory: Workaround possible compilation failures

- cmake/set_host_flags.cmake
- src/stdgpu/impl/unordered_base_detail.cuh
In device code, we use `printf` to display warnings and errors to the user. However, as indices might be 32-bit or 64-bit depending on the configuration, this may lead to warnings at compile time. Since CUDA only supports `printf` in device code, suppress the warnings for now.
In the future, the new `std::format` (C++20) will solve the issue. However, we need to wait until the support is sufficient.
> cmake,src: Handle format warnings

- src/stdgpu/impl/atomic_detail.cuh
The arithmetic and bit operations of `atomic` and `atomic_ref` use SFINAE to properly disable these operations for non-arithmetic types. Since the helper template types of these member functions are only used for SFINAE, their names were ignored in the member function definitions. Although this seems to be valid C++ code, some compilers may have problems to deduce the types. Also mention the template type names in the member function definitions to fix this issue.
> atomic: Fix missing template type names in the function definitions

- scripts/build_debug.sh
- scripts/build_release.sh
- scripts/create_documentation.sh
- scripts/install.sh
- scripts/run_tests_debug.sh
- scripts/run_tests_release.sh
- scripts/setup_debug.sh
- scripts/setup_release.sh
- scripts/utils/configure_debug.sh
- scripts/utils/configure_release.sh
- scripts/utils/create_empty_directory.sh
Previously, some scripts print an informative message on the console while others just execute the desired action. Add the missing prints and also tell all the scripts to exit early if a command fails. Furthermore, refactor common subscripts into a `utils` directory. This improves the overall structure and consistency.
> scripts: Improve console output and internal structure

- azure-pipelines.yml
- scripts/ci/openmp_debug.sh
- scripts/ci/openmp_release.sh
- scripts/utils/download_dependencies.sh
- scripts/utils/download_thrust.sh
Due to the recent enhancements and especially the recently added OpenMP backend (#32), we can integrate and run CI to verify code changes. Setup Azure Pipelines CI for this purpose.
> General: Add Azure Pipelines CI

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
The host memory allocator class called `safe_pinned_host_allocator` suggests that memory will always be pinned. Since there is an OpenMP backend now, this does not hold anymore and is more of an implementation detail anyways. Furthermore, this is inconsistent with the device (`safe_device_allocator`) and managed (`safe_managed_allocator`) variants. Rename it to `safe_host_allocator` and keep the old version (marked as deprecated) to maintain compatibility.
> memory: Add safe_host_allocator and deprecate safe_pinned_host_allocator

- azure-pipelines.yml
- scripts/ci/openmp_debug.sh
- scripts/ci/openmp_release.sh
- scripts/utils/install_cmake_ubuntu1804.sh
The steps to install a recent CMake version are backed into the CI configuration file. Furthermore, the execution of the unit tests is included into the build step. Split out both into a dedicated file/step to improve the structure. Furthermore, use `apt-get` instead of `apt` to improve stability and fix a warning.
> CI: Improve structure of scripts

- README.md
- azure-pipelines.yml
- doc/stdgpu/index.doxy
- scripts/utils/set_cxx_compiler_ubuntu.sh
- src/stdgpu/attribute.h
- src/stdgpu/cstddef.h
- src/stdgpu/platform.h
Most of the platform-specific functions already had reasonable fallbacks for any non-tested compiler such as Clang. Thus, the project already compiles fine with Clang although some warnings related to C++17 are still present. Fix the platform detection and warnings to provide full Clang support. Furthermore, add it to the CI tests.
> General: Add Clang support

- azure-pipelines.yml
- scripts/ci/configure_openmp_debug.sh
- scripts/ci/configure_openmp_release.sh
The CI scripts were refactored in #37. Further refine them by separating the configuration from the build step.
> CI: Split project building into separate step

- README.md
The `README` and `doc/stdgpu/index.doxy` files share a lot of content. However, as Markdown and Doxygen have a slightly different set of formatting rules, the content also slightly differs in each files. Partially address this by using `-` as the list item indicator in the `README` file which is supported by both of them.
> README: Improve consistency with doxygen version

- README.md
The title, i.e. the first header, in the README file should be centered. Fix the broken attempt by using the align attribute of the `<h1>` tag.
> README: Fix alignment of title

- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
- test/stdgpu/vector.inc
Although the `vector` class implements a significant part of the C++ container API, it still has some limitations. Partially address them by implementing some missing functions and relaxing the requirements of the template type T. Furthermore, perform some cleanups.
> vector: Add at(), shrink_to_fit() and remove CopyAssignable requirement from type T

- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- test/stdgpu/deque.inc
Since `deque` and `vector` have very similar implementations, the recent improvements to `vector` in #44 can also be applied to `deque`. Incorporate them to partially address the limitations of the current implementation.
> deque: Add at(), shrink_to_fit() and remove CopyAssignable requirement from type T

- examples/cuda/container_kernel.cu
- examples/cuda/thrust_towards_ranges.cu
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- test/stdgpu/unordered_datastructure.inc
In contrast to all other containers, `unordered_map` and `unordered_set` have a 2-parameter version of `createDeviceObject` which is difficult to use since it requires the user to balance both "capacity" values and imposes a strict constraint to the first parameter. Add a 1-parameter version of this function (without such a constraint) that automatically estimates a suitable number of buckets and excess entries for the requested container capacity. Furthermore, add a `max_load_factor` function that returns the current/default maximum load factor that is taken into account for above estimation. Deprecate the old- 2-parameter function to encourage users to port/use the new version.
> unordered_{map,set}: Add single-parameter createDeviceObject function

- doc/Doxyfile.in
- src/stdgpu/attribute.h
- src/stdgpu/config.h.in
- src/stdgpu/contract.h
- src/stdgpu/memory.h
- src/stdgpu/platform.h
Doxygen also includes macro definitions in the generated documentation. Since this step incorporates the macro definition by default, users might wonder about the actual values that are exposed to them. However, since most of these values are not meaningful at all without proper platform and backend context, hide them and just explain the formal meaning instead.
Furthermore, doxygen recognizes `#cmakedefine` but not `#cmakedefine01`unfortunately. Workaround this by manually defining the macros if doxygen has been detected.
> documentation: Include config.h and cleanup macro definitions

- CHANGELOG.md
Until now, released versions of the library as well as the related changes are shown at GitHub's release page. However, the library package itself does not provide this information, so users need to go back to GitHub if they want to know what has changed in a new version. Follow common best practices and include a `CHANGELOG.md` file which contains the summaries of all releases and will be updated with every new release.
> General: Add changelog file

- CONTRIBUTING.md
Until now, there is no explicit guide about the contribution process. Since it is not always obvious what standards and workflow a project follows, this would significantly help new users. Therefore, follow common best practices and include a respective `CONTRIBUTING.md` file.
> General: Add contributing file

- README.md
- doc/stdgpu/index.doxy
- doc/style.css
The `README` file as well as the main page of the built documentation provide an overview of the project and describe various aspects of the library. However, some aspects may be difficult to grasp from their visual presentation. Improve the readability and extend the project description to let readers immediately catch what the project does and how certain aspects work.
> README,doc: Significantly improve description and readability

- examples/openmp/thrust_towards_ranges.cpp
A simpler factory function for `unordered_map` and `unordered_set` has been introduced in #46. However, the port to this new function is incomplete causing warnings. Port the overlooked OpenMP example to fix the warning.
> examples: Fix missing port to non-deprecated functions

- src/stdgpu/bitset.cuh
- src/stdgpu/impl/bitset.inc
- src/stdgpu/impl/bitset_detail.cuh
Up to now, the `bitset` class defines the most important functions for atomic bitwise manipulation and access. Extend its capabilities by implementing more functions to get closer to `std::bitset` and `boost::dynamic_bitset`.
> bitset: Add further missing member functions

- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/mutex.cuh
The `mutex_ref` class was designed to decouple the locking functionality from the array API of `mutex_array`. Due to the recent improvements of the internally used `bitset` (see #53), this class could be made more lightweight by holding a `bitset::reference` instead of the the whole `bitset` as well as the bit position. Furthermore, a nested reference proxy class makes the array-like API of `mutex_array` look more natural and emphasizes that reference objects tightly belong to it. Introduce a new `mutex_array::reference` class having the same API as `mutex_ref` and implicitly deprecate `mutex_ref`.
> mutex: Add mutex_array::reference class and deprecate mutex_ref

- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- src/stdgpu/vector.cuh
A further shortcoming of the container API is the lacking `Allocator` template parameter. Since the container are designed to operate on the device, the `allocator_type` is known. Add the definition and the respective `get_allocator()` function.
> Container: Add get_allocator() function

- src/stdgpu/vector.cuh
Until now, a specialization of `vector<bool>` is not given. Since the naming convention regarding `bitset` is still not decided (see #54), disallow the usage of `vector<bool>` since the implementation may not meet user expectation. This may be relaxed in the future.
> vector: Disallow non-defined bool specialization

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- test/stdgpu/deque.inc
- test/stdgpu/vector.inc
In comparison to the C++ standard library, our GPU containers still impose stricter requirements to the template type. Similar to #44 and #45, remove the requirement of being `DefaultConstructible` to allow for more use cases. Furthermore, fix the `clear()` function of `vector` and `deque` which still required the `CopyAssignable` property to the type.
> Container: Remove DefaultConstructible requirement from template type

- doc/Doxyfile.in
In #32, the OpenMP backend has been introduced. However, since the functions are considered as internal implementation details, they should not appear in the documentation. Fix the doxygen configuration to exclude it.
> doc: Fix missing exclude of internal OpenMP backend

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/memory.h
The allocation and destruction behavior of the container has been updated recently (see #58) to allow for more use cases. This includes changes to the `clear()` functions which now destroy all stored elements. Add new `destroy*` functions defined in C++17 to `memory` to simplify this step and reduce the coupling to the internals of the `memory` module.
> memory: Add and use destroy* functions

- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/memory.h
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- src/stdgpu/vector.cuh
The containers use `default_allocator_traits` as well as the `allocate()` and `deallocate()` functions of its allocator directly. Although this approach was sufficient to relax several restrictions, it is inconsistent and does not reflect the desired behavior specified in the C++ standard. Introduce `allocator_traits<Allocator>` which resolves this problem and provide a standardized access the allocators. Deprecate the old `default_allocator_traits` which do not model the interface correctly. Note that the current implementation is oversimplified and always uses the fallback solution rather than detecting the capabilities of `Allocator`. Furthermore, this fixes an attribute issue in the recently introduced `get_allocator()` functions (see #56).
> memory: Add allocator_traits and deprecate old specialized version

- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/mutex.cuh
The recent introduction of `mutex_array::reference` (see #55) introduced a regression in the old `mutex_ref` class, i.e. the new porting aid function, which leads to compilation errors when using the CUDA backend. Change the attributes of the porting aid function from `STDGPU_HOST_DEVICE` to `STDGPU_DEVICE_ONLY` to fix this issue.
> mutex: Fix attribute of mutex_ref porting aid

- CMakeLists.txt
- NOTICE
- README.md
- cmake/code_coverage.cmake
- cmake/config_summary.cmake
- doc/stdgpu/index.doxy
- scripts/run_coverage.sh
A further step to improve the reliability of the project is to collect code coverage data. Add code to allow for the generation of local code coverage reports. In the future, this may also be automated using CI tools.
> General: Add code coverage report generation

- src/stdgpu/impl/unordered_base_detail.cuh
In #61, `allocator_traits` have been introduced. However, during the port to this new class, a regression in the deprecated 2-parameter `createDeviceObject` factory function of `unordered_base` has been introduced leading to compilation failure. Fix this issue by calling the `allocate()` function with the correct number of parameters.
> unordered_base: Fix allocate() call

- src/stdgpu/deque.cuh
The `deque` class needs to compute the occupied entries when building a device range. However, since the internal function `occupied(index_t)` is private, the respective internal functor for computation must be a friend class. Otherwise, a compilation error occurs. Fix this issue by making the internal functor a friend class.
> deque: Fix compilation error when calling device_range()

- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
`unordered_map` and `unordered_set` both use the shared `detail::unordered_base` class as a member and delegate their function calls to it. However, there is an inconsistency in the `cbegin` and `cend` functions where the const versions of `begin` and `end` respectively are called. Although this leads to the same behavior by design, it is still misleading and may have other side effects. Fix this issue by calling the correct member functions.
> unordered_map,unordered_set: Fix delegate calls to unordered_base

- src/stdgpu/impl/unordered_base_detail.cuh
The range-based insert function as well as the new `max_load_factor()` function may fail to compiler when instantiated using the CUDA backend. Since there is no respective test at the moment, these issues have not been discovered earlier. Fix both of them. In the future, the coverage will increase so that such regressions will (hopefully) disappear.
> unordered_base: Fix compilation errors with CUDA backend

- test/stdgpu/CMakeLists.txt
- test/stdgpu/algorithm.cpp
- test/stdgpu/atomic.inc
- test/stdgpu/bit.cpp
- test/stdgpu/deque.inc
- test/stdgpu/functional.cpp
- test/stdgpu/iterator.cpp
- test/stdgpu/limits.cpp
- test/stdgpu/memory.inc
- test/stdgpu/ranges.cpp
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
- test/stdgpu/vector.inc
A further step to improve the reliability of the library and to reduce the likelihood of introducing regressions is the extension of the unit tests to perform explicit template instantiation. This not only ensures that every function, including the not-yet-tested ones, will compile but also makes the code coverage report a lot more realistic since these functions are currently discarded in the report. Although the list of instantiations is not totally complete, this significantly improves the overall (build) coverage.
> test: Explicitly instantiate templates

- CMakeLists.txt
- README.md
- doc/stdgpu/index.doxy
- scripts/utils/install_cmake_ubuntu1804.sh
The current minimum required CMake version is set to 3.13 since the project uses some of its newly introduced features. However, the project is configured to use the `NEW` behavior of more recent CMake policies until version 3.15. Since the CI uses the newest version, this effectively only verifies builds where the minimum required version would be set to 3.15.
This caused a further implicit dependency getting unnoticed so far. When building on Windows, a further requirement is the `NEW` behavior of [CMake policy CMP00091](https://cmake.org/cmake/help/latest/policy/CMP0091.html). Fix this issue by increasing the minimum required CMake version. Futhermore, increase the maximum  version where policies are set to `NEW` to the most recent version 3.16.
> cmake: Fix minimum required version

- README.md
- azure-pipelines.yml
- cmake/code_coverage.cmake
- scripts/ci/configure_openmp_lcov.sh
- scripts/utils/install_lcov_ubuntu1804.sh
Due to the recent support of generating code coverty information (see #65), this process can now be automated by the CI. Setup a respective task in Azure Pipelines CI and upload the report to codecov.io. Furthermore, add the respective badge to the `README` file.
> General: Add codecov CI task

- test/stdgpu/algorithm.cpp
The `clamp()` function in the `algorithm` module is not tested at all. Extend the test cases to improve the coverage.
> algorithm: Extend unit tests

- test/stdgpu/atomic.inc
The `operator<op>=` functions with `<op>= {+, -, |, &, ^}` of the `atomic` class are not yet covered in the unit tests. Extend the test suite to fix this problem.
> atomic: Add tests for operator equals functions

- test/stdgpu/ranges.cpp
The `ranges` module provides lightweight wrappers around a pair of iterators. In comparison to the `iterator` module, it lacks unit tests. Add he respective unit tests to improve the test coverage of the `ranges` module.
> ranges: Add unit tests

- test/stdgpu/unordered_datastructure.inc
Although both `unordered_map` and `unordered_set` have probably the most extensive unit test suite, their code coverage is rather low. This is partially caused by the plethora of "read" operations to obtain certain kinds of information regarding their state. Extend the test suite to cover more of their operations and to increase the coverage.
> unordered_map,unordered_set: Extend unit tests

- test/stdgpu/unordered_datastructure.inc
The code coverage of `unordered_map` and `unordered_set` has been recently improved (see #77), but it is still incomplete. Take a further step towards full coverage by extending the unit tests even further. This also fixes a minor bug in #77.
> unordered_map,unordered_set: Further extend unit tests

- cmake/cuda/set_device_flags.cmake
- cmake/set_host_flags.cmake
- test/stdgpu/CMakeLists.txt
- test/stdgpu/memory.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
Deprecated functions are currently not tested at all since they induce warnings in the build process. Suppress these warnings exclusively for the test executable target to avoid further noise. Furthermore, add tests for the deprecated functions in the `unordered_map`, `unordered_set`, `memory` and `mutex` modules.
> test: Also include deprecated functions into unit tests

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
In order to make the issue management and reporting process easier, GitHub supports issue templates. Add templates for both bug reports and feature requests to improve the interaction with the community.
> General: Add issue templates

- README.md
- doc/stdgpu/index.doxy
- scripts/install_debug.sh
- scripts/install_release.sh
Due to the recent CMake version fix (see #71), we can now depend on further features of this version. Port the install script to the new native command-line interface which has been introduced in CMake 3.15. This also adds support for multi-configuration generators.
> scripts: Port install script to native CMake install command-line interface

- src/stdgpu/atomic.cuh
- src/stdgpu/impl/atomic_detail.cuh
- test/stdgpu/atomic.inc
In #75, more unit tests have been introduced to increase the test coverage. However, some functions are still not yet tested. Extend the tests to cover all defined functions. Furthermore, add operator-versions of `load()` and `store()` and fix the behavior of `compare_exchange_{weak,strong}`.
> atomic: Fix compare_exchange and add more operators as well as tests

- test/stdgpu/deque.inc
- test/stdgpu/memory.inc
- test/stdgpu/vector.inc
Some (member) functions are still not yet covered by the test suite. Address this issue by extending the unit tests of the `memory`, `deque` and `vector` modules.
> test: Improve coverage of several (member) functions

- README.md
In addition to build testing and code coverage tracking, static analysis can be used to detect bugs and provide a further measure for code quality. Since the project uses Coverity Scan for static analysis, add the respective badge to the README.
> README: Add coverity badge

- cmake/cuda/set_device_flags.cmake
- cmake/set_host_flags.cmake
- examples/cuda/thrust_towards_ranges.cu
- examples/openmp/thrust_towards_ranges.cpp
- src/stdgpu/impl/bitset.inc
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/iterator_detail.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/mutex.inc
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/iterator.h
- test/stdgpu/atomic.inc
- test/stdgpu/bitset.inc
- test/stdgpu/cuda/atomic.cu
- test/stdgpu/deque.inc
- test/stdgpu/iterator.cpp
- test/stdgpu/memory.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
- test/stdgpu/vector.inc
In order to ensure a high usability and reliability of the library, it should build without warnings even in the presence of strict warning settings which may be imposed by user projects. Consider variable shadowing and fix related warnings. Note that this warning will be disabled by default since older supported thrust versions do not fulfill these stricter settings.
> General: Fix shadow warnings

- src/stdgpu/deque.cuh
- test/stdgpu/bit.cpp
- test/stdgpu/functional.cpp
- test/stdgpu/limits.cpp
- test/stdgpu/memory.inc
Some of the recent test coverage improvements result in warnings emitted by the Clang compiler. Although none of them causes potential harm, they still need to be addressed. Fix them to allow for clean Clang builds.
> General: Fix Clang warnings

- src/stdgpu/CMakeLists.txt
To install header files, a blacklist approach is currently employed. However, as the internal structure of the project evolved over time, this list should have been updated as well but actually was not. Therefore, some auxiliary and source files will be accidentally installed. Use a whitelist approach which is easier to maintain, especially once #38 has been addressed.
> cmake: Fix selection of header files for installation

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- test/stdgpu/memory.inc
Similar to `destroy_at` which got introduced in C++17, we are now getting a `construct_at` function in C++20. Add a respective GPU-callable version of `construct_at` to simplify the implementation of related classes in the `memory` module and extend the support of the latter.
> memory: Add construct_at function

- cmake/cuda/set_device_flags.cmake
- cmake/set_host_flags.cmake
- examples/createAndDestroyDeviceObject.cpp
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/ranges_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- test/stdgpu/atomic.inc
- test/stdgpu/cuda/atomic.cu
- test/stdgpu/cuda/device_info.cpp
- test/stdgpu/deque.inc
- test/stdgpu/functional.cpp
- test/stdgpu/memory.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
- test/test_utils.h
In order to improve the reliability and reduce the likelihood of introducing regressions, higher warning standards are required. Increase the warning level by further accounting for conversion, sign comparison, float equality, and shadowing. Furthermore, fix the occurring warnings.
> General: Increase warning level and fix conversion and float-equal warnings

- test/stdgpu/deque.inc
- test/stdgpu/vector.inc
The unit tests of the non-const `operator[]` and `at()` functions for both `deque` and `vector` fail due to an overflow which has been revealed when using 64-bit indices. Fix this issue by using a smaller container size such that the transformed values fit into an `int`.
> deque,vector: Fix overflow in test

- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/impl/bitset.inc
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/functional_detail.h
- src/stdgpu/impl/iterator_detail.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/openmp/impl/memory.cpp
- test/stdgpu/cstdlib.cpp
- test/stdgpu/functional.cpp
- test/stdgpu/memory.inc
- test/stdgpu/unordered_datastructure.inc
- test/test_utils.h
In #98, the warning level has been increased. This caused several sign-conversion warnings to appear when building with Clang. Fix them to suppress this noise.
> General: Fix sign-conversion warnings

- cmake/set_host_flags.cmake
- src/stdgpu/cstddef.h
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- test/stdgpu/main.cpp
A long standing issue were the inconsistent format specifiers when using the `index_t` type. Since it can be either 32-bit or 64-bit and the respective specifiers even differ between platforms, using a single fixed specifier such as `%d` causes several warnings and may also be unsafe. Fix this issue by introducing a `STDGPU_PRIINDEX` specifier macro similar to the ones defined in `<cinttypes>` which adapts to the platform and provides the correct native specifier.
> General: Fix format warnings

- src/stdgpu/impl/ranges_detail.h
- src/stdgpu/ranges.h
- test/stdgpu/ranges.cpp
The `memory` and `iterator` modules consistently use `index64_t` to specify sizes. However, `ranges` uses the configurable `index_t` type which may be different from `index64_t`. Add a corresponding `index64_t` constructor version to both `device_range` and `host_range` and deprecate the `index_t` version (only implicitly to avoid unnecessary noise).
> ranges: Add index64_t constructor and deprecate index_t version

- README.md
- cmake/config_summary.cmake
- doc/stdgpu/index.doxy
- src/stdgpu/CMakeLists.txt
Some library options merely expose implementation details and, hence, may not provide any value to users or even lead to confusion:
- `STDGPU_ENABLE_AUXILIARY_ARRAY_WARNING` and `STDGPU_ENABLE_MANAGED_ARRAY_WARNING` both just print a warning if a certain code path to extend support to host-only (.cpp) files is chosen.
- `STDGPU_USE_FAST_DESTROY` disables proper safe destruction of arrays by skipping the destructor calls which lead to unexpected  behavior if the destructor is not trivial.
- `STDGPU_USE_FIBONACCI_HASHING` exposes an implementation detail regarding the mapping from hashes to buckets in  `unordered_map` and `unordered_set`.
Deprecate these options to encourage users to stick with the current, safe default values.
> General: Deprecate misleading/obsolete cmake options

- src/stdgpu/impl/memory.cpp
The safe memory system currently relies on global variables for atomics and mutexes as well as for the internal `allocation_manager` class. However, global variables typically indicate bad design and should be avoided in general. Get rid of all of them by moving the instances of `allocation_manager` to the internal `dispatch_allocation_manager` function, which now also acts as the singleton function, and by significantly simplifying the internal `allocate` and `deallocate` logic.
> memory: Cleanup global variables and simplify allocate/deallocate logic

- azure-pipelines.yml
- scripts/utils/install_openmp_ubuntu1804.sh
Up to now, we assumed that the OpenMP runtime package is also installed in the Ubuntu 18.04 image of Azure Pipelines. Since Ubuntu itself does not strictly impose a hard dependency when installing Clang but rather only a suggestion, this assumption is not always valid. In particular, the last update of the image seems to break it. Fix the problem by explicitly installing the required package.
> CI: Fix potentially missing OpenMP runtime package

- src/stdgpu/bit.h
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- test/stdgpu/bit.cpp
Internally in `createDeviceObject`, `unordered_base` computes the next power of two of the requested size which is used as the number of buckets. Since this kind of function is quite common, there is  a `ceil2` function (and `floor2` respectively) in the upcoming C++20 standard. Add both of them and remove the internal auxiliary version in `unordered_base`. Furthermore, cleanup the unit test of `bit` and fix a minor bug there.
> bit: Add ceil2 and floor2 functions

- cmake/cuda/set_device_flags.cmake
- cmake/set_host_flags.cmake
- test/stdgpu/algorithm.cpp
- test/stdgpu/bit.cpp
- test/stdgpu/cmath.cpp
- test/stdgpu/cstdlib.cpp
- test/stdgpu/functional.cpp
- test/stdgpu/unordered_datastructure.inc
- test/test_utils.h
In contrast to GCC and Clang, the used warning level for MSVC was rather low. Enable more warnings for MSVC and fix the newly appearing ones in the unit tests.
> General: Increase MSVC warning level and fix related warnings

- CMakeLists.txt
- README.md
- cmake/config_summary.cmake
- cmake/cuda/set_device_flags.cmake
- cmake/set_host_flags.cmake
- doc/stdgpu/index.doxy
- scripts/ci/configure_openmp_debug.sh
- scripts/ci/configure_openmp_release.sh
Many bugs in the project have been unveiled by increasing the warning level and handling all warnings in general. Add an option to tell the compiler to treat warnings as errors. This enables the CI to detect regressions and potentially unsafe changes more faithfully. By default, this option is set to `OFF` for backwards compatibility.
> cmake: Add option to treat warnings as errors

- azure-pipelines.yml
- doc/CMakeLists.txt
- doc/Doxyfile.in
- scripts/utils/install_doxygen_ubuntu1804.sh
In #108, an option was added to treat warnings as errors. Since doxygen has a similar option, namely `WARN_AS_ERROR`, bugs in the documentation such as missing documentation or spelling errors can now also be detected. Add a respective CI job to catch any documentation-related compilation warnings.
> General: Add CI job for documentation creation

- src/stdgpu/bit.h
- src/stdgpu/cstdlib.h
- src/stdgpu/cuda/bit.cuh
- src/stdgpu/cuda/impl/bit_detail.cuh
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/cstdlib_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- test/stdgpu/bit.cpp
- test/stdgpu/cuda/bit.cu
In the most recent draft of the upcoming C++20 standard, the functions in `<bit>` have been renamed to better highlight their intention. Apply these changes also to our GPU-capable `bit.h` header and deprecate the old versions. For the recently introduced `floor2` and `ceil2` functions, we can simply rename them since they are not contained in any released version yet.
> bit: Rename functions to match most recent draft of C++20

- src/stdgpu/impl/unordered_base_detail.cuh
- test/stdgpu/unordered_datastructure.inc
The mapping from hash values to bucket indices either uses Division Hashing (via modulus) or Fibonacci Hashing. However, since the latter requires attention for some corner cases, its logic needs to be more sophisticated. Factor this logic into a dedicated function and handle these cases more clearly. Furthermore, improve its robustness by applying a mixing operation to the input hash value and add a unit test for the bucket hit distribution.
> unordered_map,unordered_set: Improve robustness of Fibonacci Hashing

- src/stdgpu/bit.h
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/bitset_detail.cuh
Some functions in the `bit` module do not specify relevant post conditions. Fix this issue and cleanup an unnecessary dependency of `bitset` to `limits`.
> bit,bitset: Fix missing post-conditions and remove unnecessary dependency

- azure-pipelines.yml
Recently, the codecov task defined in the Azure Pipelines CI YAML file silently failed since something regarding the upload token seems to have changed for pull requests. Independently of being a potential regression in Azure Pipelines CI or codecov CI, this issue can be addressed on our side by explicitly passing the upload token to the upload script. This makes the CI task more robust. In addition to that, also tell the upload script to return failure (i.e. 1) if the uploading process failed.
> CI: Fix codecov task

- README.md
- doc/stdgpu/index.doxy
The CMake detection of dependencies and requirements has been improved and clarified in #92 #94 #96. Although these dependencies are stated in the prerequisites section of the README, its structures as well as the OS-specific installation details are not perfectly clear. Restructure this section to display all information consistently and make it easily extensible in case support for further backends (e.g. ROCm) or operating systems (e.g. Ubuntu 20.04) will be added in the future.
> README,doc: Restructure prerequisites section and add more details

- README.md
- doc/stdgpu/index.doxy
The `README` file has been significantly overhauled in #50 and #114. However, the order of the sections might not be intuitive enough for new users and visitors. Move the examples subsection to a more prominent place in the beginning of the `README` to motivate example use cases and connect them to the philosophy of the library. This strengthens the overall motivation part and reduces the focus on the technical compilation part.
> README,doc: Move examples to a more promiment place

- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/impl/iterator_detail.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/iterator.h
- src/stdgpu/openmp/impl/memory.cpp
- src/stdgpu/openmp/memory.h
- test/stdgpu/cuda/device_info.h
- test/stdgpu/openmp/device_info.h
Over time, some files were heavily refactored to improve their reliability. However, there is often some leftovers of this process including header includes. Cleanup these includes. Furthermore, make the internal `workaround_*` functions in the `memory` module mandatory to be defined by the backend modules. This improves the consistency of the required interfaces to implement a backend and clearly expresses the intent that this is not considered an optional feature.
> src,test: Improve consistency and cleanup includes

- test/stdgpu/cuda/device_info.cpp
- test/stdgpu/openmp/device_info.cpp
In #118, the includes were cleaned up. During this cleanup, the `device_info.cpp` files were not checked properly, so the lack of a proper include to their respective header files was not discovered there. Add the respective includes such that these files also follow common conventions.
> test: Fix missing include in device_info cpp files

- src/stdgpu/impl/ranges_detail.h
- src/stdgpu/ranges.h
- test/stdgpu/ranges.cpp
The API of the `ranges` module, which aims to model the C++20 ranges library in a significantly simplified yet still useful manner, is still rather limited. Add additional constructors to `host_range`, `device_range` and `transform_range` as well as `size()` and `empty()` functions and some typedefs. Furthermore, replace the non-const `begin()` and `end()` functions with equivalent const versions and implicitly deprecate the non-const ones. This is a small step towards a more useful `ranges` module.
> ranges: Add size() and empty() functions as well as additional constructors

- test/stdgpu/algorithm.cpp
- test/stdgpu/cmath.cpp
- test/stdgpu/cuda/atomic.cu
- test/stdgpu/cuda/bit.cu
- test/stdgpu/functional.cpp
- test/stdgpu/iterator.cpp
- test/test_utils.h
There are still some inconsistencies regarding the `std` namespace usage and other minor potential flaws which may be detected by the high warning level. Fix a conversion warning which has been unveiled recently. Furthermore, use the namespaced `std::size_t` rather than `size_t` consistently throughout the code and tests.
> test: Fix conversion warning and missing namespace

- scripts/utils/download_thrust.sh
Recently, the master/development branch of thrust regressed which causes failures in our CI (see [this issue](https://github.com/thrust/thrust/issues/1093)). Use a fixed version, i.e. the currently latest released/tagged version, rather than the latest development commit.
> scripts: Use released thrust version

- src/stdgpu/impl/ranges_detail.h
In #122, the API of the `ranges` module has been extended. However, on older compilers such as NVCC 10.0, this causes compilation errors where the default constructor of the internal `select` functor is missing. Fix this issue by adding the respective default constructor.
> ranges: Fix compilation error with select functor

- cmake/rocm/Findthrust.cmake
ROCm 3.1 and below exported rocthrust without the `roc::` namespace which has been fixed in ROCm 3.3. However, this now causes errors on our side. Workaround this issue by supporting both versions. This workaround can be dropped once ROCm 3.3 becomes the minimum required version.
> cmake: Workaround bug in imported rocthrust target name

- .clang-tidy
- CMakeLists.txt
- README.md
- cmake/config_summary.cmake
- cmake/setup_clang_tidy.cmake
- doc/stdgpu/index.doxy
- examples/CMakeLists.txt
- src/stdgpu/CMakeLists.txt
- test/stdgpu/CMakeLists.txt
clang-tidy allows to improve code quality and reduce the likelihood of introducing unnoticed regressions. Add native support for clang-tidy to build and analyze the project with clang-tidy.
Here, the config file `.clang-tidy` contains an initial set of enabled warnings after experimenting with some options. This list will be updated and extended in the future.
> General: Add clang-tidy support

- examples/cuda/thrust_towards_ranges.cu
- examples/openmp/thrust_towards_ranges.cpp
- examples/rocm/thrust_towards_ranges.cpp
- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/impl/bitset.inc
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/iterator_detail.h
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/mutex.inc
- src/stdgpu/impl/ranges_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/iterator.h
- src/stdgpu/mutex.cuh
- test/stdgpu/atomic.inc
- test/stdgpu/bitset.inc
- test/stdgpu/deque.inc
- test/stdgpu/iterator.cpp
- test/stdgpu/memory.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
A common pitfall are single-parameter constructors since they allow implicit conversions between classes/types. Since this behavior is usually undesired, they should be marked `explicit`. Fix all of these undesired cases. For the few desired ones, suppress the clang-tidy warnings.
> examples,src,test: Fix hicpp-explicit-conversion warnings

- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- test/stdgpu/atomic.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
Although `return` statements after `if` clauses do not require braces, it is still useful to have them for readability reasons. Fix these clang-tidy warnings.
> src,test: Fix hicpp-braces-around-statements warnings

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- test/test_utils.h
`else` statements after a `return` in the preceding `if` clause seem intuitive at first glance since they follow natural language. However, the `else` statement is superfluous from a technical point of view. Follow clang-tidy recommendations and drop these statements.
> src,test: Fix readability-else-after-return warnings

- src/stdgpu/impl/limits_detail.h
- test/stdgpu/bitset.inc
`limits` exploits the fact that boolean values may implicitly be converted to `1` and `0` integer values. This is useful for computing the number of digits for types that may be signed or unsigned such as `char` and `wchar_t`. Fix the related clang-tidy warnings by explicitly casting the boolean values to integers making this intentional usage clear.
> src,test: Fix readability-implicit-bool-conversion warnings

- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/iterator_detail.h
Assignment operators usually coincide with the copy-assignment operator. However, for some cases such as `atomic` and `atomic_ref`, other forms of assignment operators are actually desired. Suppress the related clang-tidy warnings for these cases. Furthermore, fix the wrong return types of the internal iterator proxy classes.
> src: Fix misc-unconventional-assign-operator warnings

- examples/createAndDestroyDeviceObject.cpp
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/openmp/impl/atomic_detail.h
- test/stdgpu/atomic.inc
- test/stdgpu/bit.cpp
- test/stdgpu/cstdlib.cpp
Bit operations on signed integer types include cases with undefined behavior making this potentially dangerous. Fix some cases where casting to a proper unsigned type is safe. Suppress the warning if the behavior there is intentional, e.g. for the operations on `atomic` and `atomic_ref`.
> examples,src,test: Fix hicpp-signed-bitwise warnings

- .clang-tidy
- src/stdgpu/contract.h
- src/stdgpu/cstdlib.h
- src/stdgpu/impl/bitset.inc
- src/stdgpu/openmp/impl/memory.cpp
- test/stdgpu/bitset.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
There are still a few clang-tidy warnings left. Fix them to enable clean builds with clang-tidy enabled. Furthermore, slightly adjust the set of considered warnings.
> src,test: Fix more clang-tidy warnings

- azure-pipelines.yml
- scripts/ci/configure_openmp_clang_tidy.sh
- scripts/utils/install_clang_tidy_ubuntu1804.sh
After the recent major warning cleanup, this process of detecting further potential bugs and regressions through clang-tidy can now be automated. Add a proper CI job which automatically performs clang-tidy checks and treats warnings as errors to ensure that they are not missed.
> CI: Add clang-tidy job

- src/stdgpu/compiler.h
- src/stdgpu/platform.h
Macros in the `compiler` and `platform` are implemented through magic numbers to distinguish the individual values. However, the ranges of many different groups of macros overlap which leads to unexpected behavior if mixing them up. Use unique identifiers for all valued macros. This fixing potential weird behavior in such cases.
Note that mixing up macros is a bug itself and needs to be fixed. This change helps to unveil such erroneous cases.
> compiler,plaform: Use unique numbers as internal macro definitions

- .clang-tidy
- examples/contract.cpp
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/cmath_detail.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/ranges_detail.h
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/platform.h
- src/stdgpu/ranges.h
- test/stdgpu/bitset.inc
- test/stdgpu/cmath.cpp
- test/stdgpu/deque.inc
- test/stdgpu/main.cpp
- test/stdgpu/memory.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
- test/stdgpu/vector.inc
Recent versions of clang-tidy contain a larger set of diagnostics. Fix these newly appearing warnings to further improve the code quality.
> examples,src,test: Fix clang-tidy-8 warnings

- .clang-tidy
- examples/createAndDestroyDeviceArray.cpp
- examples/createAndDestroyDeviceObject.cpp
- examples/cuda/thrust_interoperability.cu
- examples/cuda/thrust_towards_ranges.cu
- examples/openmp/thrust_interoperability.cpp
- examples/openmp/thrust_towards_ranges.cpp
- examples/rocm/thrust_interoperability.cpp
- examples/rocm/thrust_towards_ranges.cpp
- src/stdgpu/impl/limits_detail.h
- test/stdgpu/algorithm.cpp
- test/stdgpu/atomic.inc
- test/stdgpu/bit.cpp
- test/stdgpu/bitset.inc
- test/stdgpu/cmath.cpp
- test/stdgpu/cstdlib.cpp
- test/stdgpu/cuda/device_info.cpp
- test/stdgpu/deque.inc
- test/stdgpu/functional.cpp
- test/stdgpu/iterator.cpp
- test/stdgpu/main.cpp
- test/stdgpu/memory.inc
- test/stdgpu/mutex.inc
- test/stdgpu/openmp/device_info.cpp
- test/stdgpu/rocm/device_info.cpp
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
- test/stdgpu/vector.inc
In addition the recent warning fixes (see #140), there are still some warnings left. Fix these `readability-magic-numbers` warnings to ensure clean builds under `clang-tidy-8`.
> examples,src,test: Fix readability-magic-numbers warnings

- test/stdgpu/bitset.inc
- test/stdgpu/mutex.inc
Inconsistent namespace usage for `std::size_t` has been cleaned up in #124. However, there are also inconsistencies for `std::uint8_t`. Add the missing namespace qualifications to make them consistent.
> test: Fix missing namespace for uint8_t

- src/stdgpu/bitset.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/mutex.cuh
Recent compilers such as GCC 10 and Clang 10 emit a stricter set of warnings. Fix the newly appearing `-Wdeprecated-copy` warning by explicitly defining a copy constructor. Since ROCm's HCC compiler seems to have problems with the C++11 default version, we fallback to old C++98 style copy constructors.
> bitset: Fix deprecated-copy warning

- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
The `bitset` module is the only consumer of the `cstdlib` module. `cstdlib` itself only contains a helper function to compute the quotient and remainder of an integer division for the special case of power-of-2 divisors, which mixes parts of `cstdlib` and `bit`. Remove the dependency to `cstdlib` such that this (helper) module may be deprecated in the future.
> bitset: Remove dependency to cstdlib

- cmake/set_host_flags.cmake
- src/stdgpu/compiler.h
- src/stdgpu/platform.h
In #119, automatic dispatching support has been added to the `platform` module. However, this caused a regression in `attribute` where `STDGPU_HAS_CXX_17` becomes undefined due to include changes. Since the latter is closer related to `compiler` rather than `platform`, move it to that place. Furthermore, extend the set of warnings to avoid such regressions in  the future.
> platform: Move STDGPU_HAS_CXX_17 to compiler

- cmake/set_host_flags.cmake
- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/hip/impl/memory.cpp
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/openmp/impl/memory.cpp
- test/stdgpu/iterator.cpp
Using `-Weverything`, Clang analyzes the code for any possible warning it knows about. Since not all of them are meaningful for most projects, we also do not enable it by default. Nevertheless, fix some of these warnings to cleanup the code.
> src,test: Fix some minor warnings

- src/stdgpu/contract.h
The host versions of the `STDGPU_{EXPECTS,ENSURES,ASSERTS}` macros are internally defined as `if` statements which do not require semicolons at the end of the statement. However, this may lead to confusing warnings mentioning superfluous semicolons. Even worse, users might omit the semicolon at the end of the macros and get the impression that this version is more robust and produces less noise.
Fix this undesired behavior by enforcing a semicolon on the user side. This fixes potential warnings and makes wrong usage of the macros, i.e. omitting the semicolon, a compiler error.
> contract: Enforce user semicolon for all possible expansions

- CMakeLists.txt
- README.md
- azure-pipelines.yml
- cmake/config_summary.cmake
- cmake/setup_cppcheck.cmake
- doc/stdgpu/index.doxy
- examples/CMakeLists.txt
- scripts/ci/configure_openmp_cppcheck.sh
- scripts/utils/install_cppcheck_ubuntu1804.sh
- src/stdgpu/CMakeLists.txt
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/platform.h
- test/stdgpu/CMakeLists.txt
- test/stdgpu/main.cpp
Similar to the recently added clang-tidy support (see #129), cppcheck allows for static analysis of the code to detect potential bugs and regressions. Add native support for cppcheck and a corresponding CI job to automate this process.
> General: Add cppcheck support

- src/stdgpu/contract.h
In #148, the macros in the `contract` module have been fixed to enforce semicolons at macro invocation. However, this fix was incomplete and does not cover the case when the contract checks are disabled. Replace it with a more robust version which is based on the definition of `assert`.
> contract: Fix user semicolon enforcement for disabled checks

- test/stdgpu/cuda/device_info.cpp
- test/stdgpu/hip/device_info.cpp
Although many warnings have been fixed, there are still some double-promotion warnings left in backend code. Fix them to allow for clean builds using the CUDA and HIP backends.
> test: Fix double-promotion warnings in backend code

- cmake/cuda/set_device_flags.cmake
- src/stdgpu/cuda/impl/atomic_detail.cuh
The CUDA backend only supports GPUs with Compute Capability (CC) 3.5 and higher since some internal `atomic<op>` functions are only natively implemented for these GPUs. Backport the functions that are missing in CC 3.0 to add support for it and lower the respective minimum required CC from 3.5 to 3.0.
> General: Add support for Compute Capability 3.0 in CUDA backend

- cmake/cuda/set_device_flags.cmake
Due to the recently improved support for older Compute Capabilities (see #153), the logic to generate CUDA architecture flags can now be simplified. Drop the obsolete checks for the minimum required and maximum supported CCs.
> cmake: Simplify architecture flag generation in CUDA backend

- src/stdgpu/compiler.h
The `compiler` module uses the `__CUDA_ARCH__` define to detect NVCC. Since it is the only supported device compiler providing this define at the moment, the detection apparently seems to work. However, other compilers that also provide this define, e.g. Clang, may be added in the future which results in violating the current assumption. Use `__NVCC__` instead of `__CUDA_ARCH__` to fix this bug.
> compiler: Fix NVCC detection

- src/stdgpu/impl/bit_detail.h
- test/stdgpu/bit.cpp
- test/stdgpu/cstdlib.cpp
- test/stdgpu/functional.cpp
- test/stdgpu/iterator.cpp
- test/stdgpu/memory.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
Although many signed/unsigned warnings have been fixed, there are still a few of these conversion warnings left which are mostly detected by MSVC's `/W3` and `/W4` warning levels. Fix these warnings to make builds under MSVC cleaner.
> src,test: Fix several signed/unigned MSVC warnings

- src/stdgpu/impl/ranges_detail.h
- src/stdgpu/ranges.h
In #102, a `index64_t` constructor has been added to the `ranges` classes and the old `index_t` constructors have been deprecated. However, if the latter coincides with the former, i.e. `STDGPU_USE_32_BIT_INDEX` is set to `OFF`, this results in compilation errors due to rereclarations and redefinitions. Fix this error by conditionally enabling the deprecated `index_t` version.
> ranges: Fix compilation 64-bit index type

- test/stdgpu/atomic.inc
- test/stdgpu/bitset.inc
- test/stdgpu/deque.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
In comparison to the `src` code, variables are often passed by value in the `test` code. This may impact the performance and only works since containers perform shallow copy rather than deep copy. Pass all containers by const reference rather than by value to fix these potential performances issues and make a possible future transition to deep copy easier.
> test: Pass containers by const reference to functors

- test/stdgpu/bit.cpp
In the unit test of the `bit` module, a potential bit shift by a negative amount may occur which may happen if an intermediate result is zero. Fix this case which causes undefined behavior by adding a check for this intermediate result.
> bit: Fix potential negative bit shift in unit test

- test/CMakeLists.txt
GMock is not used by the unit tests, but it is still built by default. Turn off the respective options to disable building it. This slightly improves compilation times.
> test: Disable unused GMock

- src/stdgpu/cstdlib.h
The `sizedivPow2` function in the `cstdlib` module resulted from the initial design of the library and its application in `bitset`. As the library evolved over time, it turned out that its design is not very clear and just mixes parts of `cstdlib` and `bit`. Since its last usage in `bitset` has been removed in #145, deprecate `sizedivPow2` as well as `sizediv_t`.
> cstdlib: Deprecate sizedivPow2

- README.md
- doc/stdgpu/index.doxy
Although the `README` improved a lot in the past, it still lacks a short summary of the offered features. Extend the introduction by highlighting the GPU data structures and containers and by listing the remaining headers which complement them.
> README,doc: Extend introduction and mention the library features more prominently

- doc/Doxyfile.in
- src/stdgpu/config.h.in
- src/stdgpu/cuda/atomic.cuh
- src/stdgpu/hip/atomic.h
- src/stdgpu/openmp/atomic.h
Unfortunately, many links in the documentation are not working and some symbols are still missing. Fix these issues by adjusting the doxygen's configuration and adding the missing documentation.
> doc: Fix several minor documentation bugs

- README.md
- doc/stdgpu/index.doxy
In #162, the introduction has been extended. Take a step further and add links to the documentation as well as includes in the code snippets. This makes the introduction more accessible and improves navigation speed.
> README,doc: Add links to documentation and includes in code snippets

- src/stdgpu/cstddef.h
In #47, the macro definitions/initializers have been hidden to make the documentation clearer. However, the corresponding changes to `cstddef` were not made. Cleanup this module as well to make the documentation more consistent.
> cstddef: Hide initializers for clearer documentation

- src/stdgpu/impl/limits_detail.h
- src/stdgpu/limits.h
- test/stdgpu/limits.cpp
In contrast to `hash` from `functional`, the `numeric_limits` traits do not have a proper documentation since the declaration is completely hidden. Move the member declarations out of the implementation and add the respective documentation. Furthermore, add the implementation for the non-specialized template as well as a respective test.
> limits: Add implementation for non-specialized template and documentation for every type

- doc/Doxyfile.in
- src/stdgpu/attribute.h
- src/stdgpu/compiler.h
- src/stdgpu/config.h.in
- src/stdgpu/contract.h
- src/stdgpu/cstddef.h
- src/stdgpu/cuda/platform.h
- src/stdgpu/functional.h
- src/stdgpu/hip/platform.h
- src/stdgpu/impl/functional_detail.h
- src/stdgpu/iterator.h
- src/stdgpu/limits.h
- src/stdgpu/memory.h
- src/stdgpu/openmp/platform.h
- src/stdgpu/platform.h
We strive for documenting every class, member, and function to provide an as complete documentation as possible. However, some internal implementation details were documented as well. Remove all unnecessary documentation to avoid confusion.
> doc: Cleanup unnecessary documentation

- README.md
- doc/Doxyfile.in
- doc/DoxygenLayout.xml
- doc/README.md
- doc/stdgpu/chapters.doxy
- doc/stdgpu/index.doxy
- doc/style.css
- examples/README.md
Although the documentation is linked at GitHub, these links are not easily discoverable in the `README`. Furthermore, users might look into `doc/` to find the documentation which, however, will be a dead end. Add a dedicated section in the `README` to point at the documentation and create a local `README` in `doc/` with the same section content. Furthermore, create a local `README` in `examples/` as well to explain the structure and requirements of the examples. Finally, clean up the documentation style and remove unintuitive doxygen pages.
> README,doc: Add subdirectory READMEs and clean up documenation

- README.md
- doc/stdgpu/index.doxy
In #171, `<h4>` was used to format the text. However, it introduces additional whitespace before the text. Replace `<h4>` with `<b>` to reduce this spacing and make the text look a bit more balanced.
> README,doc: Reduce spacing around bold text

- src/stdgpu/contract.h
- src/stdgpu/openmp/platform.h
- test/stdgpu/memory.inc
For the OpenMP backend, the `platform` macros currently always report code to be `STDGPU_CODE_HOST`. Since some `STDGPU_HOST_DEVICE` annotated function may use different paths for host and device code and the device path may contain backend-specific optimizations, this choice will lead to backend-specific code being ignored.
Change the detection code to always report `STDGPU_CODE_DEVICE` rather than `STDGPU_CODE_HOST`. Note that for such functions using different code paths, these paths should result in equivalent behavior anyways.
> platform: Change detection of device code for OpenMP

- test/stdgpu/memory.inc
In #174, some `memory` unit test has been slightly changed to remove conditional behavior. However, since this was required when using the CUDA backend, these tests were not well-designed. Improve these unit tests to work for all backends by moving from static variables to member variables.
> memory: Improve construct* and destroy* unit tests

- src/stdgpu/atomic.cuh
- src/stdgpu/cuda/atomic.cuh
- src/stdgpu/cuda/impl/atomic_detail.cuh
- src/stdgpu/hip/atomic.h
- src/stdgpu/hip/impl/atomic_detail.h
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/openmp/atomic.h
- src/stdgpu/openmp/impl/atomic_detail.h
Up to now, `atomic` and `atomic_ref` do not specify the memory order that they will enforce. In the C++ standard library, the default memory order for calls to them is sequential consistency, so users will assume that stdgpu also enforces this order. However, we did not explicitly enforced this which might lead to runtime errors or dead locks. Explicitly make all atomic member functions, including `load()` and `store()` follow sequentially consistent ordering to ensure consistency with the C++ standard library.
> atomic: Make all operations follow sequentially consistent ordering

- src/stdgpu/cuda/atomic.cuh
- src/stdgpu/hip/atomic.h
- src/stdgpu/openmp/atomic.h
Although the backend API is not contained in the public API documentation (as it is an implementation detail from the user's point of view), the backend functions of `atomic` are not fully documented. Add documentation to the template parameter to all of these functions.
> atomic: Add backend documentation of template parameter

- src/stdgpu/impl/limits_detail.h
The probably last long-standing warning is thrown by MSVC with the CUDA backend enabled stating that long double will be treated as double in device code. This is caused by MSVC's implementation of `HUGE_VALL` which is expands to `(long double)INFINITY`. Suppress this warning by using `HUGE_VAL` for MSVC instead which avoids explicitly casting to `long double`.
> limits: Suppress long double device code warning with MSVC

- src/stdgpu/CMakeLists.txt
In case `CMAKE_BUILD_TYPE` is not set by the user, expanding this variable will result in collapsing it in an expression and causing configuration errors in `if` clauses. Fix such an error by using the variable rather than its expanded value.
> cmake: Fix error with unspecified build type

- CMakeLists.txt
- src/stdgpu/CMakeLists.txt
- src/stdgpu/cuda/CMakeLists.txt
- src/stdgpu/hip/CMakeLists.txt
When installing stdgpu to a certain location, the package currently contains absolute paths which hard-code the installation destination. However, this prohibits moving the package to another location and forces a re-installation with the modified path. Make the package relocatable by removing all absolute paths to reduce this installation burden for users.
> cmake: Make installable package relocatable

- README.md
- doc/README.md
- doc/stdgpu/index.doxy
The documentation section in the `README` only contains a link to the API documentation. Extend it to also cover the thrust algorithms documentation as well as our research paper explaining the design. This way, the features and intended use cases should become more obvious to new users.
> README,doc: Extend documentation section

- examples/openmp/bitset.cpp
- examples/openmp/deque.cpp
- examples/openmp/mutex_array.cpp
- examples/openmp/unordered_map.cpp
- examples/openmp/unordered_set.cpp
- examples/openmp/vector.cpp
In the new examples, the containers are passed by value, even in the ones for the OpenMP backend. While this is required for the CUDA and HIP backends, pass-by-reference should still be preferred for the OpenMP backend. Fix this these minor issues detected by Coverity Scan.
> examples: Pass containers by reference for OpenMP backend

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
`operator[]` should not perform bounds checks. Remove these checks by making `at()` call `operator[]` rather than the other way around.
Fixes #184
> deque,vector: Remove bounds check in operator[]

- README.md
- cmake/hip/Findthrust.cmake
- cmake/hip/set_device_flags.cmake
- doc/stdgpu/index.doxy
- scripts/ci/configure_hip_debug.sh
- scripts/ci/configure_hip_release.sh
- src/stdgpu/CMakeLists.txt
- src/stdgpu/compiler.h
- src/stdgpu/contract.h
- src/stdgpu/hip/CMakeLists.txt
- src/stdgpu/hip/platform.h
- test/stdgpu/iterator.cpp
ROCm 3.5 deprecated the HCC compiler and all newer versions recommend HIP-Clang to be the device compiler. Port the HIP backend to this new compiler and bump the required version of ROCm. This way, we also get rid of the HCC-specific workarounds and limitations.
> General: Port HIP backend to ROCm 3.5+

- CMakeLists.txt
- cmake/cuda/set_device_flags.cmake
CMake 3.18+ adds a new abstraction upon the CUDA architecture flag generation. Use this new property to support Clang as the CUDA compiler.
> cmake: Use CUDA_ARCHITECTURES property

- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
- test/stdgpu/deque.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
In #56, all containers got a member function to return its allocator object. However, no explicit member object has been introduced so far due to compatibility reasons. Add this new allocator member object now and use it in the member functions. This makes the containers work correctly for allocators that have a state.
Fixes #62
> Container: Add allocator member

- src/stdgpu/bitset.cuh
- src/stdgpu/impl/bitset_detail.cuh
This removes the deprecated functions in the `bitset` module.
Partially addresses #51
> bitset: Remove deprecated functions

- src/stdgpu/impl/ranges_detail.h
- src/stdgpu/ranges.h
- test/stdgpu/ranges.cpp
This removes the deprecated functions in the `ranges` module.
Partially addresses #51
> ranges: Remove deprecated functions

- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- test/stdgpu/unordered_datastructure.inc
This removes the deprecated functions in the `unordered_map` and `unordered_set` modules.
Partially addresses #51
> unordered_map,unordered_set: Remove deprecated functions

- README.md
- cmake/config_summary.cmake
- doc/stdgpu/index.doxy
- src/stdgpu/CMakeLists.txt
- src/stdgpu/config.h.in
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/memory.h
This removes the deprecated CMake options and the related functionality.
Partially addresses #51
> cmake: Remove deprecated options

- test/stdgpu/bitset.inc
Some host member functions of `bitset` were not properly tested, but at the same time not reported to be untested. Add the missing tests to increase the test coverage.
> bitset: Add more tests for host member functions

- test/stdgpu/atomic.inc
- test/stdgpu/bitset.inc
- test/stdgpu/deque.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
Empty containers, i.e. the ones not created via `createDeviceObject(...)`, are also valid objects and some functions implement special handling of this case to avoid segmentation faults. However, these corner cases were not covered by the test suite. Add the missing tests to increase the code coverage.
> Container: Add coverage for handling empty containers

- cmake/cuda/FindCUDAToolkit.cmake
For comparability with older CMake versions, we currently provide our own oversimplified version of the `FindCUDAToolkit.cmake` module. Although this works sufficiently well, the upstream version provides more libraries and supports more use cases. Fall back to the upstream module if it is available. In the future, this may become useful to add support for Clang as the CUDA compiler.
> cmake: Use CMake's FindCUDAToolkit.cmake if available

- src/stdgpu/contract.h
- test/stdgpu/CMakeLists.txt
- test/stdgpu/contract.cpp
The contracts are defined as macros to handle the different scenarios and use cases. However, expressions containing commas, which is often the case in the presence of templates, are rejected by the compiler if not properly guarded by parentheses. Although this behavior is well-known from the `assert(...)` macro, it still limits the usability. Add support for such unguarded expressions and introduce dedicated unit tests for the `contract` macros.
> contract: Add support for expressions containing commas

- examples/cuda/bitset.cu
- examples/cuda/deque.cu
- examples/cuda/mutex_array.cu
- examples/cuda/unordered_map.cu
- examples/cuda/unordered_set.cu
- examples/cuda/vector.cu
CUDA uses unsigned integers to represent thread and thread block numbers. Since we use signed integers for indices, this may raise compiler warnings. Fix these sign comparison warnings by explicit casting.
> examples: Fix sign comparison warnings in CUDA examples

- README.md
- cmake/cuda/set_device_flags.cmake
- doc/stdgpu/index.doxy
- src/stdgpu/compiler.h
- src/stdgpu/contract.h
- src/stdgpu/cuda/platform.h
CMake 3.18 introduced support for Clang as the CUDA compiler. Having more than a single compiler at hand is highly beneficial to improve the portability and platform independence. Add detection for CUDA-Clang and enable the CUDA platform annotations for it. 
In the future, we may reduce the minimum requirements to Clang 10. However, this requires to turn off C++ extensions due to a bug in Clang which has been fixed in Clang 11.
> General: Add support for CUDA-Clang compiler

- cmake/hip/Findthrust.cmake
The HIP backend searches for rocthrust as a dependency to stdgpu. However, the respective `Findthrust.cmake` module only searches in the default path `/opt/rocm` which may not be always suitable especially in the presence of multiple installations of ROCm. Consider the `ROCM_PATH` regular and environment variables as a hint to the desired ROCm installation and fall back to the default path if they are not set.
Issue #186
> cmake: Honor ROCM_PATH variables

- .clang-tidy
- src/stdgpu/bitset.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/iterator_detail.h
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- test/stdgpu/contract.cpp
- test/stdgpu/memory.inc
As more recent versions of clang-tidy are available, e.g. through Ubuntu 20.04, and this tool comes with an increasing set of warnings, we should keep up the pace as well. Fix these new warnings to ensure clean builds with such recent versions. This is required to use newer CI images.
> src,test: Handle more recent clang-tidy warnings

- cmake/setup_cppcheck.cmake
- examples/contract.cpp
- src/stdgpu/impl/iterator_detail.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/memory_detail.h
- test/stdgpu/functional.cpp
Similar to #211, recent versions of cppcheck detect more potential bugs. Fix these new warnings to ensure clean builds and prepare for upgrading to new CI images.
> src,test: Handle more recent cppcheck warnings

- src/stdgpu/atomic.cuh
- src/stdgpu/cuda/atomic.cuh
- src/stdgpu/cuda/impl/atomic_detail.cuh
- src/stdgpu/hip/CMakeLists.txt
- src/stdgpu/hip/atomic.h
- src/stdgpu/hip/impl/atomic_detail.h
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/openmp/atomic.h
- src/stdgpu/openmp/impl/atomic_detail.h
- test/stdgpu/atomic.inc
In #176, we changed the enforced memory ordering in `atomic` and `atomic_ref` to be sequentially consistent. Although implementing precise control over the memory order without having access to compiler internals is extremely difficult and often not possible. Extend the expected backend interface to also provide a synchronization primitive for sequential consistency. Based on this, try to mimic the all memory orders as close as possible with stricter or equal semantics. This gives more fine-grained control over the memory ordering.
Note that stricter memory orderings than requested are often imposed due to above limitations. Using too weak orderings in user code may lead to unexpected failures. It is generally recommended to use sequentially consistent ordering, which is still the default …
> atomic: Add control for memory ordering

- src/stdgpu/openmp/impl/atomic_detail.h
- src/stdgpu/openmp/platform.h
Refactoring the backend interface of `atomic` in #214 led to simpler code and relaxed requirements to the implementation. Add internal detection for the OpenMP version and conditionally make use of atomic clauses for any suitable operation if such clauses are available. This improves the performance for some atomic operations.
> atomic: Use OpenMP atomic clauses if available

- src/stdgpu/atomic.cuh
- src/stdgpu/cuda/atomic.cuh
- src/stdgpu/cuda/impl/atomic_detail.cuh
- src/stdgpu/hip/atomic.h
- src/stdgpu/hip/impl/atomic_detail.h
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/openmp/atomic.h
- src/stdgpu/openmp/impl/atomic_detail.h
- test/stdgpu/atomic.inc
The `atomic` class provides various member functions to perform different atomic operations, including addition, subtraction and bitwise operations. For a unified interface with the C programming language, the C++ standard also provides type aliases for the defined specializations and non-member free functions pointing to the corresponding members. Add these functions and typedefs to our `atomic` module to allow for using these alternative interfaces.
> atomic: Add non-member atomic functions

- src/stdgpu/atomic.cuh
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/type_traits.h
- test/stdgpu/atomic.inc
Some member functions of `atomic` are conditionally enabled based on its template type `T`. Although we already use a quite readable version to implement this without making the interface too ugly, there is still some room for improvement. Factor out the implementation of the conditional check and move it a new macro `STDGPU_DETAIL_OVERLOAD_IF()` and a corresponding version for out-of-class function definitions. This makes function signatures much easier to read.
> type_traits: Add macro for conditional overloading and apply in atomic

- src/stdgpu/impl/type_traits.h
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
The range-based `insert` and `erase` functions of `unordered_map` and `unordered_set` currently allow to pass device pointers of the key or value types or const qualified versions thereof. This not only limits their usability but also results in duplicated code. Unify them to a template based version as defined in the C++ standard to overcome this limitation.
> unordered_map,unordered_set: Unify and relax range-based insert and erase

- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
In #220 support for the transparent `find` function has been added to `unordered_map` and `unordered_set`. Extend this by also providing transparent `count` and `contains` functions in a similar way. Furthermore, simplify the tests by automatically checking the transparent versions in the helper functions as well.
> unordered_map,unordered_set: Add transparent count and contains functions

- src/stdgpu/impl/unordered_base_detail.cuh
We often observed fluctuating code coverage in `unordered_base`'s internal `find_previous_entry_position` function. Due to the inherent multi-threading nature of the algorithms we test, there has been significant likelihood that the fallback path will not be triggered. Fix this problem by unifying the two possible code paths through a single return statement.
> unordered_base: Fix fluctuating coverage

- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/cuda/platform.h
- src/stdgpu/cuda/platform_check.h
- src/stdgpu/deque.cuh
- src/stdgpu/hip/platform.h
- src/stdgpu/hip/platform_check.h
- src/stdgpu/impl/platform_check.h
- src/stdgpu/mutex.cuh
- src/stdgpu/openmp/platform_check.h
- src/stdgpu/queue.cuh
- src/stdgpu/stack.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- src/stdgpu/vector.cuh
The cross-platform attribute `STDGPU_DEVICE_ONLY` requires compilation of the file, where it is used, with the appropriate device compiler. Although the `sizeof` approach prints the included error message, it still produces much duplicates and noise making the error hard to understand. Replace this check with a preprocessor error that must be explicitly included in the related header files. This approach produces quite short and descriptive error messages at the cost that it must be applied manually. However, this advantages outweigh the slightly increased maintenance burden.
Issue #187 #209
> General: Improve compilation error generation for wrong device compiler

- CMakeLists.txt
Some library files are missing during the coverage report generation since the respective compiler flags are only applied to the tests and not to the compiled library. Fix this issue by setting up the respective compiler flags as early as possible. While at it, move all options up to a common place to make them easier to find.
> cmake: Fix missing coverage of library files

- src/stdgpu/bit.h
- src/stdgpu/cuda/atomic.cuh
- src/stdgpu/cuda/impl/atomic_detail.cuh
- src/stdgpu/hip/atomic.h
- src/stdgpu/hip/impl/atomic_detail.h
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/functional_detail.h
- src/stdgpu/openmp/atomic.h
- src/stdgpu/openmp/impl/atomic_detail.h
- test/stdgpu/bit.cpp
Reinterpreting an object, e.g. an `int`, as another object, e.g. a `float`, may easily result in undefined behavior due to type aliasing rules. Add `bit_cast` as a safe alternative to cast between types. This fixes undefined behavior for the `float`, `double`, and `long double` specializations of `hash`.
In addition to the above changes, also clean up the conditional overloading mechanism by using the recently introduced `STDGPU_DETAIL_OVERLOAD_IF` macro.
> bit: Add bit_cast

- src/stdgpu/impl/unordered_base_detail.cuh
- test/stdgpu/unordered_datastructure.inc
The `clear` function of `unordered_base` uses the thread-based `erase` function. Since clearing a data structure is a special case of the general erase, we can exploit this knowledge to improve the performance. Change the approach to reset the state of all member variables separately using their optimized clear function. This results in a significant performance improvement for large containers.
> unordered_map,unordered_set: Improve performance of clear

- src/stdgpu/functional.h
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/functional_detail.h
- test/stdgpu/functional.cpp
Similar to #226, `bitset` uses the thread-based versions of the `set` , `reset`, and `flip` functions to implement to variants operating on all bits. Exploit this knowledge to change the state without atomic operations. This significantly improves the performance by a large factor.
> bitset: Improve performance of set, reset, flip

- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
- test/stdgpu/vector.inc
Although `vector` implements many useful functions, it is currently still not easy to concurrently insert a range of values while preserving their order. If ordering is not crucial, `back_inserter` can be used to `push_back` the elements to the vector. Implement `insert` and `erase` for the special case of inserting at or erasing from the end of the container. This allows to conveniently perform the former operation and, at the same time, it can be used as a faster version of the latter use case. Furthermore, `erase` allows to efficient remove ranges of elements from the container.
> vector: Add insert and erase functions

- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- test/stdgpu/deque.inc
- test/stdgpu/vector.inc
The `device_range` function of `deque` internally uses `vector` to collect all indices. Improve the performance of this operation by using the `insert` function. This revealed two bugs in `device_range` itself as well as in `clear`. In the former case, some entries may be missed and not included into the range. In the latter case, the destruction of elements for a full container will be accidentally skipped. Fix these two bugs as well and extend the unit tests to cover these cases.
> deque: Improve performance of device_range and fix some bugs

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
As a follow up on #226, we can now also make use of the more efficient `insert` function of `vector`. Replace the copy call, which effectively just uses `push_back`, with that. This further improves the performance of `clear` as well as `createDeviceObject`.
> unordered_map,unordered_set: Further improve performance of clear

- src/stdgpu/hip/CMakeLists.txt
HIP's CMake support provides a version file to properly check for a minimal requirement. However, it is configured to report incompatibility between major versions. Since ROCm 4.0 has been released for a while, this breaks our compilation if nor ROCm 3.x version is installed in parallel. Remove the explicit version check for now to fix this issue.
> cmake: Fix build with ROCm 4.x

- CMakeLists.txt
- src/stdgpu/impl/vector_detail.cuh
- test/stdgpu/bit.cpp
In #224, all options have been moved to a uniform place. However, this broke the default value of the `STDGPU_SETUP_COMPILER_FLAGS` option whose default value is determined dynamically. Fix its initialization and as well as all warnings introduced in the meantime.
> cmake: Fix compiler flags setup option

- CMakeLists.txt
- README.md
- doc/stdgpu/index.doxy
Clang as the CUDA compiler has been supported for a while. In the meantime, not only Clang 11 has been backported to Ubuntu 20.04, but unfortunately some regressions in libstdc++ 10 slipped in as well. Improve the CUDA Clang support by disabling C++ extensions which workarounds compilation errors. With this workaround enabled, Clang 10 can also be supported.
> General: Improve support for CUDA Clang

- README.md
- doc/stdgpu/index.doxy
The thrust repository has been moved so the original link changed as well. Although there is automatic redirection in place, update the link to point to the new location.
> README,doc: Update link to thrust repository

- CMakeLists.txt
CMake 3.19 and 3.20 are out for quite some time. After reviewing the newly introduced policies, bump the maximum supported policy version to the currently most recent CMake version.
> cmake: Update support for CMake 3.20

- CMakeLists.txt
- cmake/cuda/set_device_flags.cmake
The CUDA CC detection helps to automatically select a suitable architecture for the current machine. Although this provides an optimal value if the detection succeeds, failures result in errors during generation. This prevents several use cases such as build testing the library and any dependents e.g. using CI. Improve the architecture detection by explicitly respecting any user-specified values and falling back to CMake's default architectures if no GPU can be detected.
> cmake: Improve detection of CUDA architectures

- src/stdgpu/cuda/impl/atomic_detail.cuh
Support for the CUDA Compute Capability 3.0 has been added in #153. However, the intermediate CC 3.2 has not been considered. Although the CUDA documentation states that it also lacks official support, compilation fails because it actually is officially defined. Fix this issue by only defining our fallback for CC 3.0.
> atomic: Fix compilation for CC 3.2

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/type_traits.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/memory.h
- test/stdgpu/deque.inc
- test/stdgpu/memory.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
- test/stdgpu/vector.inc
In compliance with the C++ standard, our containers as well as the memory API perform destruction operations on deletion. However for trivially destructible types, this results in a no-op for each element, but the underlying loop cannot always be automatically optimized away. Improve the performance by detecting this case and skipping the whole operation.
> General: Optimize performance of destroy calls

- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
The `insert` and `erase` functions of `unordered_map` and `unordered_set` optimize performance by first checking if the requested key is already contained as an early stopping criteria. However, this check is performed twice for each attempt, the first one being in the loop condition and the second one in the underlying `try_insert` and `try_erase` functions which also perform that optimization. Expose the operation status of the latter functions to simplify the loop condition and get rid of one of the checks. This improves the performance when no early stopping can be performed.
> unordered_map,unordered_set: Improve performance of insert and erase

- scripts/utils/download_thrust.sh
thrust 1.13 has been recently released. In order to check compatibility with their recent developments, upgrade out scripts to use this version over the older 1.11 release.
> scripts: Upgrade to thrust 1.13

- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
When introducing the allocator member variable for all containers in #191, a typo in their name was introduced. Fix this by renaming the variables to from `_alloctor` to `_allocator`.
> src: Fix typo in allocator member names

- CMakeLists.txt
CMake 3.21 has been recently released. Keep up with the pace of introduced behavioral changes by bumping the maximum supported policy version.
> cmake: Update support for CMake 3.21

- src/stdgpu/cuda/CMakeLists.txt
CMake automatically infers the CUDA standard based on the specified value for the C++ standard. Although this provides a convenient default for most projects, it is better to explicitly specify it. This will ensure that a potential future behavioral change, e.g. via a policy, is already covered.
> cmake: Explicitly enforce CUDA standard

- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- test/stdgpu/memory.inc
The `iterator` API including the `size()` request function are tightly coupled to the internal memory (leak) detection system. While is a suitable solution if only the `safe_{device,host,managed}_allocator` classes are supported, it prevents opening up the API for external memory. Split the internal memory management into independent allocation and a size parts and add functions to register external memory into the size manager. This allows for further changes to open up the API.
> memory: Add register memory API

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- test/stdgpu/memory.inc
Up to now, the create/destroy API is limited to the internal `safe_{device,host,managed}_allocator` classes. In order to open up the API for custom allocators, provide new overloads. This also allows to simplify the implementation of the fixed variants and share code between all overloads.
>  memory: Add allocator-based create/destroy functions

- src/stdgpu/atomic.cuh
- src/stdgpu/impl/atomic_detail.cuh
- test/stdgpu/CMakeLists.txt
- test/stdgpu/atomic.inc
- test/test_memory_utils.cpp
- test/test_memory_utils.h
- test/test_memory_utils_detail.h
Although `atomic` internally uses an allocator to construct the internal value, it did not expose any API regarding this relationship. Extend its API and add support for custom allocators. This makes `atomic` become closer to a container and makes the differences to the C++ standard library easier to understand.
> atomic: Add support for custom allocators

- examples/cuda/bitset.cu
- examples/openmp/bitset.cpp
- src/stdgpu/bitset.cuh
- src/stdgpu/bitset_fwd
- src/stdgpu/deque.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/mutex.cuh
- src/stdgpu/vector.cuh
- test/stdgpu/bitset.inc
Although `bitset` internally uses an allocator to construct the internal value, it did not expose any API regarding this relationship. Extend its API and add support for custom allocators. This makes `bitset` become closer to a container (and boost's `dynamic_bitset`, see #54 for a discussion) and makes the differences to the C++ standard library easier to understand.
> bitset: Add support for custom allocators

- examples/cuda/mutex_array.cu
- examples/openmp/mutex_array.cpp
- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/mutex.cuh
- src/stdgpu/mutex_fwd
- src/stdgpu/vector.cuh
- test/stdgpu/mutex.inc
Although `mutex_array` internally uses an allocator to construct the internal value, it did not expose any API regarding this relationship. Extend its API and add support for custom allocators. This makes `mutex_array` become closer to a container and makes the differences to the C++ standard library easier to understand.
> mutex: Add support for custom allocators

- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
- src/stdgpu/vector_fwd
- test/stdgpu/vector.inc
- test/test_memory_utils.h
- test/test_memory_utils_detail.h
Although the interface of `vector` is close to the one in the C++ standard, it still has some limitations. Add support for custom allocators to narrow the gap. Custom allocators are required to be contructible and copyable on both the host and the device.
> vector: Add support for custom allocators

- src/stdgpu/deque.cuh
- src/stdgpu/deque_fwd
- src/stdgpu/impl/deque_detail.cuh
- test/stdgpu/deque.inc
Although the interface of `deque` is close to the one in the C++ standard, it still has some limitations. Add support for custom allocators to narrow the gap. Custom allocators are required to be contructible and copyable on both the host and the device.
> deque: Add support for custom allocators

- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_map_fwd
- src/stdgpu/unordered_set.cuh
- src/stdgpu/unordered_set_fwd
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
Although the interface of `unordered_map` and `unordered_set` is close to the one in the C++ standard, it still has some limitations. Add support for custom allocators to narrow the gap. Custom allocators are required to be contructible and copyable on both the host and the device.
> unordered_map, unordered_set: Add support for custom allocators

- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/deque.cuh
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/mutex.cuh
- src/stdgpu/vector.cuh
While introducing the `Allocator` template parameter, the interface of the `get_allocator` member functions has changed to allow for less restrict definitions of custom allocators. However, the allocator might still be accessed in device code. Fix missing `STDGPU_HOST_DEVICE` annotation and consider custom allocators for be constructible and copyable on both the host and the device.
> Container: Fix host device annotation for get_allocator function

- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/deque.cuh
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/mutex.cuh
- src/stdgpu/vector.cuh
- test/stdgpu/deque.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
Adding support for custom allocators for the containers increased their structure size by a considerable amount. This may negatively impact the performance and block parts of the cache unnecessarily. Minimize the size of the container structures by removing redundant member variables or replace complex members with simpler variables. As a result, the sizes should no be on par or even lower than before adding custom allocator support.
> Container: Minimize size of container structures

- src/stdgpu/impl/unordered_base_detail.cuh
When allocating instances of `unordered_map` and `unordered_set` with a very large amount of entries, e.g. ~10^8, the computation of the excess list size may suffer from numeric cancellation. This can lead to (almost) empty excess lists making the container barely usable. Fix this issue by using `long double` instead of `float` for the size computation.
> unordered_map,unordered_set: Fix numeric cancelation in excess size computation

- cmake/Findthrust.cmake
The `Findthrust.cmake` module contains common paths for system installations on Debian/Ubuntu. However, Arch-based distributions prefer to install CUDA to `/opt/cuda`. Add this path to the list of hints to allow for correctly finding thrust on these systems.
> cmake: Add further hint for thrust system path

- .clang-tidy
- examples/createAndDestroyDeviceObject.cpp
- src/stdgpu/memory.h
- test/stdgpu/mutex.inc
Clang 13 introduced more warnings that could reveal potential bugs in the source code. Fix or suppress the new warnings to make the code compile cleanly again.
> General: Fix new compiler warnings by Clang 13

- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/platform_check.h
- src/stdgpu/platform.h
The `#include` statements of the backend headers are quite complicated and required defining temporary macro names to build the path. Simplify this logic by moving it to the new internal macro function `STDGPU_DETAIL_BACKEND_HEADER()`.
> src: Simplify backend header includes

- test/stdgpu/cuda/device_info.cpp
- test/stdgpu/hip/device_info.cpp
When executing the unit tests, a summary of the properties of the used device is printed. However, if no valid device is available, bogus values are printed when executing the tests. Catch this corner case and output a clearer message stating that no device has been detected at runtime.
> test: Fix printing of properties for invalid devices

- .github/workflows/analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- README.md
- doc/stdgpu/index.doxy
- scripts/ci/configure_cuda.sh
- scripts/ci/configure_hip.sh
- scripts/ci/configure_openmp.sh
- scripts/utils/configure.sh
The recently update scripts allowed for greater flexibility, but regressed support on other shells such as `zsh`. Conditionally use the `shift` command to avoid an explicit error with `zsh` (and an implicit one with `bash`).
Furthermore, explicitly call the scripts with the `bash` command to avoid implicitly falling back to `dash`/`sh` on Ubuntu which does not support `shift`ing.
> scripts: Fix compatibility with zsh

- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- .gitignore
- scripts/ci/check_install_openmp.sh
- test/install_test/CMakeLists.txt
- test/install_test/install_test.cpp
Although we export the relevant CMake targets as well as all required information of the dependencies when installing the library, there is not formal test to verify that installed versions of `stdgpu` can actually be found out-of-the-box. Add a small test project that is based on the recommended way of finding the package (see `README.md`) and run this test for each relevant configuration in the CI.
> General: Add installation test

- .clang-tidy
- test/stdgpu/main.cpp
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
After revisiting Clang 13 support in #264, the number of  suppressed `clang-tidy` warnings increased. Revisit the list of ignored warnings and fix some of these. Since balancing the number of `NOLINT` statements over the number of completely disabled warnings is not trivial, keep the remaining setting as is.
> test: Fix more clang-tidy warnings

- CMakeLists.txt
- cmake/FindClangTidy.cmake
- cmake/FindCppcheck.cmake
- cmake/setup_clang_tidy.cmake
- cmake/setup_cppcheck.cmake
We depend on several external commonly used tools to support certain functionalities such as documentation creation, unit tests, static analysis, etc. For some of these tools, there is proper support using `Find*` modules that provide version and path information for the found components. For others, however, this information is currently missing.
Add modules for `clang-tidy` and `cppcheck` to have a reusable and more powerful way of finding and getting version information from them. Furthermore, print the version of the currently used `CMake` executable which may help to maintain compatibility across various versions.
> cmake: Provide more version information for depending tools

- .github/workflows/windows.yml
GitHub Actions support building with VS 2022 for quite a while. Add a respective CI job to also test the library with this more recent compiler and ensure clean builds.
> CI: Add job with Windows 2022 image

- src/stdgpu/CMakeLists.txt
- src/stdgpu/cuda/CMakeLists.txt
- src/stdgpu/cuda/device.h
- src/stdgpu/cuda/impl/device.cpp
- src/stdgpu/device.h
- src/stdgpu/hip/CMakeLists.txt
- src/stdgpu/hip/device.h
- src/stdgpu/hip/impl/device.cpp
- src/stdgpu/impl/device.cpp
- src/stdgpu/openmp/CMakeLists.txt
- src/stdgpu/openmp/device.h
- src/stdgpu/openmp/impl/device.cpp
- test/stdgpu/cuda/CMakeLists.txt
- test/stdgpu/hip/CMakeLists.txt
- test/stdgpu/main.cpp
- test/stdgpu/openmp/CMakeLists.txt
The functionality to print information for the currently used device can also be useful besides the internal unit tests. Move this functionality to the library. This does not only simplify the call in the main function of the tests and hide all backend-specific details, but also gives users more hints about their environment.
> src: Move device info functionality from unit tests

- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- CMakeLists.txt
- NOTICE
- README.md
- cmake/add_uninstall_target.cmake
- cmake/cmake_uninstall.cmake.in
- doc/stdgpu/index.doxy
- scripts/uninstall.sh
Although the implementation of the uninstall target is also used in many other projects and quite robust in general, testing it with the `install.sh` scripts resulted in an error. Fix this issue and move the target creation to a separate file. Furthermore, add the missing license information and update the related code snippets. To avoid such regressions in the future, extend the installation test in the CI to also cover the new `uninstall.sh` script.
> cmake: Fix uninstall target

- src/stdgpu/functional.h
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/functional_detail.h
- src/stdgpu/unordered_set.cuh
- test/stdgpu/atomic.inc
- test/stdgpu/deque.inc
- test/stdgpu/functional.cpp
- test/stdgpu/memory.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
In terms of functors, we currently rely on the `equal_to`, `identity`, and `plus` classes provided by thrust. Remove the coupling to those functions and fix some missing includes.
> functional: Remove coupling to thrust functors

- src/stdgpu/algorithm.h
- src/stdgpu/impl/algorithm_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- test/stdgpu/algorithm.cpp
- test/stdgpu/atomic.inc
- test/stdgpu/bitset.inc
- test/stdgpu/deque.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
A common pattern of the used algorithms is a simple parallel for loop over a range of indices `[0, N)`. Since many other algorithms could be implemented in terms such a for loop as well, this will be a good starting point to consolidate the calls to thrust to a single place. Add a `for_each_index` function and port all direct functions following this pattern to the new syntax.
> algorithm: Add for_each_index

- src/stdgpu/impl/ranges_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
Due to the parallelism of the involved algorithms, we already assume that all pointers and iterators can be accessed randomly which also implies that the computing the distance between two iterators only involves a subtraction. Replace calls to `distance` by a simple subtraction. Furthermore, clean up the internal insertion function of `vector` which also relies on `distance`.
> src: Port away from distance

- test/stdgpu/atomic.inc
The `generate` function is only used in the unit tests to store a sequence of incremented and decremented indices respectively in an array to check the related operators of the `atomic` class. Port away from `generate` by rewriting the functor and using `for_each_index` instead.
> test: Port away from generate

- test/stdgpu/mutex.inc
The tests in `mutex` use `zip_iterator` and `tuple` to pass two indices to a kernel for checking the lock functionality. Port these to `for_each_index` with a single (unused) index and pass the indices to the functor instead. 
> test: Port away from zip_iterator and tuple

- src/stdgpu/impl/bitset_detail.cuh
- test/stdgpu/bitset.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
Another function that is primarily used in the unit test is `transform` to generate flags based on a successful operation which are then tested. Port these use cases to `for_each_index` to remove the dependency and to make the code look more uniform.
> src,test: Port away from transform

- test/stdgpu/bitset.inc
During the refactoring of the `bitset` unit test, the includes were also updated and cleaned up. However, this introduced a regression with `std::shuffle` which is defined in `<algorithm>`, but not directly included anymore. Fix this possible compilation error by adding the missing include.
> test: Fix missing include in bitset

- test/stdgpu/atomic.inc
- test/stdgpu/deque.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
In the unit tests, the `reduce` function is either used for summing up a sequence of numbers to check whether every number within it is actually contained, or to compute a certain quantity of a container, e.g. number of collisions. Port away from `reduce` by directly checking for the values in the former case, and using `std::accumulate` on the host in the latter case.
> test: Port away from reduce

- test/stdgpu/deque.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
The `sort` and `count_if` functions are only used in the unit tests and are already surrounded by code where both a device and host version of the involved data arrays are allocated. Port away from both of these functions by utilizing the host versions instead.
> test: Port away from sort and count_if

- test/stdgpu/unordered_datastructure.inc
The unit test of `unordered_map` and `unordered_set` use the thrust versions of the `<random>` header to generate a set of key values. Port away to the host version provided by the C++ standard library which are also already used in the unit test.
> test: Port away from random header

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/unordered_base_detail.cuh
- test/stdgpu/atomic.inc
- test/stdgpu/deque.inc
- test/stdgpu/memory.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
The trivial `thrust::for_each` invocations that directly use indexing through `thrust::counting_iterator` were ported in #281. However, there are still many other non-trivial use cases where a a different type of iterator is used. Port (almost) all of these to the new `for_each_index` function.
> src,test: Port away from for_each

- examples/cuda/unordered_map.cu
- examples/openmp/unordered_map.cpp
- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/queue_detail.cuh
- src/stdgpu/impl/stack_detail.cuh
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/queue.cuh
- src/stdgpu/stack.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_map_fwd
- src/stdgpu/unordered_set.cuh
- src/stdgpu/utility.h
- src/stdgpu/vector.cuh
- test/stdgpu/deque.inc
- test/stdgpu/memory.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/unordered_map.inc
- test/stdgpu/unordered_set.inc
- test/stdgpu/vector.inc
Several data structures including their unit tests use `thrust::pair` to have a device-side version of `std::pair`. Although we could re-implement the `pair` data structure and also fix some of thrust's limitations in their implementation, it is sufficient to only define an alias and port all use cases to the new alias. A full replacement can still be considered in the future.
> utility: Add pair as alias to thrust implementation

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/type_traits.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/memory.h
- test/stdgpu/memory.inc
The recent refactoring of `for_each` in #294 introduced a regression for `unordered_map` where the `insert` function no longer worked for a `device_ptr` of constant type as the internal cast to a raw pointer is no longer present. Fortunately, C++20 added the `to_address` function for such use cases where the raw pointer of a fancy pointer can be obtained. Add `to_address` as well as the respective unit tests to fix the regression. Furthermore, this will be useful for the remaining porting effort.
> memory: Add to_address function

- src/stdgpu/algorithm.h
- src/stdgpu/impl/algorithm_detail.h
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- test/stdgpu/algorithm.cpp
- test/stdgpu/deque.inc
- test/stdgpu/iterator.cpp
- test/stdgpu/memory.inc
- test/stdgpu/ranges.cpp
- test/stdgpu/vector.inc
The `fill`  and `copy` functions are used in the library itself as well as in the unit tests. Port away from these functions by re-implementing them in terms of `for_each_index`.
> src, test: Port away from copy and fill

- src/stdgpu/algorithm.h
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- test/stdgpu/memory.inc
- test/stdgpu/unordered_datastructure.inc
One remaining non-trivial use case of `thrust::for_each` is the unit test of `unordered_map` and `unordered_set` where the range function is checked. Since the value type of `unordered_map` is not assignable, the recently introduced `copy` in #297 cannot be used. Add `uninitialized_copy` and `uninitialized_fill` as the corresponding versions that use the copy constructor rather than copy assignment and port this use case to the new functions. This also exposes the so-far hidden `uninitialized_fill` function and adds respective unit tests for it.
> memory: Add uninitialized_copy and uninitialized_fill

- src/stdgpu/algorithm.h
- src/stdgpu/impl/algorithm_detail.h
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/memory.h
- test/stdgpu/algorithm.cpp
- test/stdgpu/memory.inc
The recently added algorithms cover most use cases to abstract over `for_each_index`. However, their signatures are not always consistent and the `*_n` versions are also missing. Clean up these inconsistencies and also port `destroy` away from thrust's `for_each`.  Furthermore, use perfect forwarding and add the respective unit tests. This ensures that, although the algorithm module should be kept minimal, all relevant variants are provided.
> algorithm,memory: Add *_n versions of algorithms and cleanup destroy

- src/stdgpu/algorithm.h
- src/stdgpu/impl/algorithm_detail.h
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/numeric_detail.h
- src/stdgpu/numeric.h
- test/stdgpu/CMakeLists.txt
- test/stdgpu/algorithm.cpp
- test/stdgpu/atomic.inc
- test/stdgpu/deque.inc
- test/stdgpu/numeric.cpp
- test/stdgpu/vector.inc
The `iota` algorithm has been added in #283 in the `algorithm` header. However, the C++ standard library defines this function in the `numeric` header along with other functions such as `transform_reduce`. Move `iota` to a newly created `numeric` module and adapt the includes of all modules relying on that function.
> numeric: Move iota from algorithm header

- src/stdgpu/impl/algorithm_detail.h
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/numeric_detail.h
- src/stdgpu/numeric.h
- test/stdgpu/numeric.cpp
Another common pattern of the used algorithms is general reduction of set of value. These values could hypothetically be computed in a parallel manner using `for_each_index` over a range of indices [0, N). Therefore, add `transform_reduce_index` as the analogue of the indexed for loop which additionally reduces the computed values and port all away from `thrust`'s `transform_reduce`.
Partially addresses https://github.com/stotko/stdgpu/issues/279
> numeric: Add transform_reduce_index

- src/stdgpu/functional.h
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/functional_detail.h
- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- test/stdgpu/functional.cpp
- test/stdgpu/memory.inc
- test/stdgpu/mutex.inc
The last two remaining `thrust` algorithms used in the library are `all_of` and `equal` which are both similar in the sense that a range of values is tested against either a unary function or a different range. Port away from both of these by replacing them with `transform_reduce_index` using the newly added `logical_and` functor. Furthermore, simplify the implementation of binary functions and clean up an obsolete include.
> src,test: Port away from equal and all_of

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
After the introduction of `for_each_index` and `transform_reduce_index` there are only a few occurrences of `counting_iterator` left. Port these remaining use cases to `iota` and clean up some qualifications.
> src,test: Port away from counting_iterator

- test/stdgpu/algorithm.cpp
- test/stdgpu/memory.inc
- test/stdgpu/numeric.cpp
After the large refactoring of the `algorithm` module and the related functions, the time to run the tests significantly increased. Reduce the array sizes of the affected tests to speed up the CI and restore a similar runtime performance as before the changes.
> test: Reduce array sizes to speed up CI

- src/stdgpu/impl/mutex_detail.cuh
The `valid()` function of `mutex_array` tests each bit individually and performs a reduction to check if all mutexes are unlocked. Use the `count()` function of `bitset` instead to simplify the code. This also significantly improves the performance for large container sizes due to the more efficient reduction of the bits in `bitset`.
Before:
```
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
stdgpu_mutex_valid/1000          0.027 ms        0.027 ms        25450
stdgpu_mutex_valid/100000        0.051 ms        0.051 ms        12299
stdgpu_mutex_valid/10000000      0.695 ms        0.694 ms          991
```
After:
``` …
```
> mutex: Improve performance of valid function

- .github/workflows/analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/style.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
GitHub Action recently warns about deprecated node.js 12 versions used in `v2` of the `checkout` action. Upgrade to `v3` as recommended to fix this warning.
> CI: Fix deprecation warning in checkout action

- .clang-format
- CMakeLists.txt
- README.md
- STYLE_GUIDE.md
- doc/stdgpu/index.doxy
- src/stdgpu/CMakeLists.txt
- src/stdgpu/cuda/CMakeLists.txt
- src/stdgpu/hip/CMakeLists.txt
C++17 has been out for quite a long time and support in all relevant compilers has matured sufficiently until now. Thus, bump the requirements of building stdgpu from C++14 to C++17. This unblocks several features and cleanups.
Issue: #314
> General: Bump required standard to C++17

- CMakeLists.txt
CMake 3.24 has been recently released. Keep up with the pace of introduced behavioral changes by bumping the maximum supported policy version.
> cmake: Update support for CMake 3.24

- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- cmake/config_summary.cmake
- scripts/ci/configure_cuda.sh
- scripts/ci/configure_hip.sh
- scripts/ci/configure_openmp.sh
- scripts/utils/verify_headers.sh
- src/stdgpu/CMakeLists.txt
- src/stdgpu/cuda/CMakeLists.txt
- src/stdgpu/hip/CMakeLists.txt
- src/stdgpu/openmp/CMakeLists.txt
CMake 3.23 and 3.24 introduce functionality to properly handle header files and also perform automatic `#include` checks. Use this new approach - if available - and extend the CI checks to also cover header verification.
Note that this slightly changes the set of installed header to only include the **currently used**  backend rather than all header files. Since this single backend will only be functional anyways (due to the compiled sources), the new approach is in fact more consistent.
> cmake: Explicitly list and process headers

- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/cuda/memory.h
- src/stdgpu/hip/impl/memory.cpp
- src/stdgpu/hip/memory.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/openmp/impl/memory.cpp
- src/stdgpu/openmp/memory.h
Since we no require at least thrust 1.9.9, drop the manual workaround for synchronizing the device in the `memory` module. This also simplifies the interface of the backends.
> memory: Drop thrust synchronization workaround

- .clang-tidy
- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/openmp/impl/memory.cpp
- test/stdgpu/bitset.inc
- test/stdgpu/contract.cpp
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
Recent versions of clang-tidy introduced further checks to improve the code quality. Although our coverage is already quite good, increase the number of checks and suppress the aliases to existing checks.
In the future, we may even maximize the coverage by unconditionally enabling all checks and providing a single list of ignored warnings.
> src,test: Enable and fix more clang-tidy warnings

- src/stdgpu/impl/bit_detail.h
C++17 also introduced `std:.byte` as a distinct type to better represent a collection of bits. Since the type aliasing rules for `reinterpret_cast` have been extended accordingly to also allow `std::byte` in addition to `char` and `unsigned char`, port the implementation of `bit_cast` to this new type.
> bit: Use std::byte in bit_cast implementation

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/type_traits.h
- src/stdgpu/memory.h
Currently, `to_address` uses a quite complex SFINAE check with the internal overload macro from the `type_traits` module. Simplify this implementation by using `if constexpr` instead. Furthermore, remove the obsolete backport of `void_t`.
> memory: Simplify to_address implementation

- src/stdgpu/atomic.cuh
- src/stdgpu/bit.h
- src/stdgpu/bitset.cuh
- src/stdgpu/cuda/atomic.cuh
- src/stdgpu/cuda/impl/atomic_detail.cuh
- src/stdgpu/functional.h
- src/stdgpu/hip/atomic.h
- src/stdgpu/hip/impl/atomic_detail.h
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bit_detail.h
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/openmp/atomic.h
- src/stdgpu/openmp/impl/atomic_detail.h
- src/stdgpu/vector.cuh
- test/stdgpu/contract.cpp
Many classes and functions are conditionally enabled based on some type properties and make use of the type traits provided by the C++ standard library. Port these traits to the new and shorter `*_v` inline variable versions to improve the readability.
> src,test: Use shorter inline variables as type traits

- benchmark/stdgpu/unordered_datastructure.inc
- src/stdgpu/CMakeLists.txt
- src/stdgpu/impl/preprocessor.h
- src/stdgpu/impl/type_traits.h
- src/stdgpu/platform.h
The internal `type_traits` module defines a macro to generate implementation-specific traits. Extend this macro by a an inline variable alias to enable using this shorter notation for our custom traits.
Furthermore, move the `STDGPU_DETAIL_CAT{2,3}` macros to a dedicated `preprocessor` module as this is required in the implementation of the alias. As a side effect, this makes the `platform` module a bit cleaner.
> type_traits: Add inline variable alias in trait generation macro

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- src/stdgpu/vector.cuh
While the use of type traits from the C++ standard library have been simplified in #333, our own implementation-specific traits are still referenced by the classic `*::value` notation. Port these traits to the newer `*_v` versions as well for consistency and better readability.
> src: Use shorter inline variables for detail type traits

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
The simplification of the implementation of `to_address` in #332 resulted in a missing-return warning with NVCC for older CUDA versions. This compiler bug has been fixed in newer version, potentially in CUDA 11.5+. Revert to the old pre-C++17 implementation but keep the new code commented for future usage when the requirements will be increased. Furthermore, clean up some namespace qualifications to improve the readability.
> memory: Fix missing-return warning in to_address with NVCC

- .clang-tidy
- src/stdgpu/iterator.h
With the recent release of clang-tidy 15, some rules are more consistently and stricter enforced. Therefore, handle them and disable the noisy const-correctness warning for now.
> src: Fix recent clang-tidy warnings

- .github/workflows/documentation.yml
The deployed documentation on https://stotko.github.io/stdgpu/ quickly gets outdated between releases. Since users are also often interested in the latest set of features, deploying the corresponding documentation will expose them to these features in a more convenient way.
Furthermore, this enables a quicker tracking of issues with the documentation not tracked by the warnings as the current state will always be visible without requiring to always manually build the documentation by hand.
> CI: Automatically deploy latest documentation

- README.md
- doc/Doxyfile.in
- doc/stdgpu/chapters.md
- doc/stdgpu/index.md
- doc/stdgpu/iterator.md
- doc/stdgpu/memory.md
- doc/stdgpu/object.md
Although Doxygen supports Markdown since version 1.8.0, this feature has not been used yet in the documentation. However, this greatly simplifies the required syntax for more complex formatting. Thus, port all additional documentation files to Markdown and additionally simplify the `README` file.
> doc: Port to Markdown files

- doc/Doxyfile.in
Although static member functions like `createDeviceObject` and `destroyDeviceObject`  were documented and respective entries are generated, these are currently not linked in the tree view. Fix this missing linking by telling Doxygen to properly extract them. While at it, also hide the additional reference text added in the header of classes to make the documentation's look cleaner.
> doc: Fix extraction of static members

- src/stdgpu/bitset.cuh
NVCC ignores host and device annotation on defaulted functions. While this has been properly handled for default constructors, a respective warning for the copy constructor of `bitset::reference` is only thrown on Windows with the CUDA backend. Thus, remove the offending annotation to silence the warning.
> bitset: Fix ignored annotation warning for defaulted copy constructor

- doc/CMakeLists.txt
- scripts/ci/configure_openmp_documentation.sh
The detection of Doxygen has been improved in #342. Since Doxygen will now be always available, the package detection message is not needed anymore. Suppress it by passing `QUIET` to `find_package`. Furthermore, remove the obsolete root path specification in the respective configure call script.
> cmake,scripts: Clean up doxygen detection

- .github/workflows/coverage.yml
- CMakeLists.txt
The currently used bash-based uploading script to codecov has been deprecated for a while. Since uploading also seems to recently become a bit unstable, this way is not future-proof anymore. Update the upload step using the more modern GitHub action provided by codecov to solve these issues.
Furthermore, add the `build` directory to the list of excluded directories to filter out googletest which is now downloaded on-the-fly and hence, does not lie within the `test` directory anymore.
> CI: Update coverage upload step

- cmake/setup_clang_format.cmake
- src/stdgpu/config.h.in
The `config.h.in` file is a placeholder for the auto-generated config file and has so far been not considered to be formatted by `clang-format`. Since the special replacement syntax of CMake breaks the automatic formatting, perform a manual correction afterwards and keep the file still excluded.
While at it, also clean up the `_fwd` extension from the file detection and also remove the unnecessary documentation of the `stdgpu` namespace which generates a bloated page in the documentation that is not referenced anywhere.
> config: Apply formatting and remove unnecessary namespace documentation

- src/stdgpu/execution.h
The `host` and `device` execution policies have been defined in #305 as aliases to the objects defined by thrust. However, the respective classes are not provided and must currently be retrieved via `decltype` and some type casting. Expose the respective classes via alias typedefs and use them to simplify the definition of the objects.
> execution: Expose host and device policy classes via aliases

- README.md
- doc/stdgpu/index.md
While most of the badges in the `README` file and the documentation main page provide useful information to users, there are also a few that may not be similarly informative. Drop them to streamline the badge list and put more focus on the other more important ones.
> README,doc: Drop less informative badges

- CMakeLists.txt
CMake 3.26 has been recently released. Keep up with the pace of introduced behavioral changes by bumping the maximum supported policy version.
> cmake: Update support for CMake 3.26

- src/stdgpu/cuda/CMakeLists.txt
- src/stdgpu/cuda/impl/device.cpp
- src/stdgpu/cuda/impl/error.h
- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/hip/CMakeLists.txt
- src/stdgpu/hip/impl/device.cpp
- src/stdgpu/hip/impl/error.h
- src/stdgpu/hip/impl/memory.cpp
The internal error handling in the CUDA and HIP backends was previously an internal detail of the `memory` backend implementation. However, this functionality is also required in the `device` implementations and currently causes a compiler warning in the HIP backend due to an unhandled return variable.  Move the error handling code to a dedicated backend-specific file and use it in both the `memory` and the `device` modules.
> src: Move backend-internal error handling into separate files

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- test/stdgpu/memory.inc
Although the `memory` module already supports custom allocators making it quite generic, the more advanced API related to automatically filled arrays still uses the default execution policies. Extend `allocator_traits` by `allocate_filled` and `deallocate_filled` functions that additionally take an execution policy as well as an initialization value as their arguments. This consolidates all required allocation functions in the traits and follows the recommended  usage from the C++ standard.
Issue: #351
> memory: Add (de)allocatate_filled functions to allocator_traits

- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/deque.cuh
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/mutex.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- src/stdgpu/vector.cuh
- test/stdgpu/atomic.inc
- test/stdgpu/bitset.inc
- test/stdgpu/deque.inc
- test/stdgpu/mutex.inc
- test/stdgpu/unordered_datastructure.inc
- test/stdgpu/vector.inc
- test/test_utils.h
Currently, all containers allow for custom allocators, but lack support custom execution policies. Add overloads to the `createDeviceObject` and `destroyDeviceObject` static member functions that additionally take an execution policy object and port the respective implementations to uniformly use `allocator_traits` for memory (de)allocation.
> src: Add execution policy overload to all container creation and destruction functions

- benchmark/CMakeLists.txt
A new release of google benchmark is available. Pull in this new version to benefit from the major improvements and cleanups.
> benchmark: Upgrade google benchmark to 1.8.0

- doc/CMakeLists.txt
A new release of the modern doxygen theme is available. Pull in this new version to benefit from the major improvements and cleanups.
> doc: Upgrade doxygen-aweseome-css to 2.2.1

- CMakeLists.txt
- cmake/config_summary.cmake
- scripts/ci/configure_openmp_documentation.sh
Documentation building is optional and excluded by default, so the actual build must be explicitly run via a respective CMake target. However, the corresponding CMake code is always parsed which includes downloading the modern doxygen theme and setting up all targets. Add a CMake option `STDGPU_BUILD_DOCUMENTATION`  to allow for completely disabling all of these steps. Furthermore, since users typically do not attempt building the documentation, set its default value to `OFF`.
> cmake: Add option to enable building the documentation

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- test/stdgpu/memory.inc
In #251, new allocator-based overloads to the create/destroy `memory` functions have been added to support custom allocators throughout all containers of the library. Since `allocator_traits` has been extended and adopted by the containers, these older functions are not used anymore and primarily only point to `allocator_traits` anyways. Drop them to streamline the `memory` API and reduce the maintenance burden.
> memory: Drop superseded allocator-based create/destroy functions

- src/stdgpu/bitset.cuh
- src/stdgpu/impl/bitset_detail.cuh
- test/stdgpu/bitset.inc
Whereas the containers operate in a sequential order and, hence, do not need custom execution policies, this lack of support becomes problematic for our GPU counterparts where aspects like controlling kernel synchronization play an important role. Add support for custom execution policies to all host functions of `bitset` running GPU kernels to allow greater control by the user.
> bitset: Add support for custom execution policies

- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/mutex.cuh
Whereas the containers operate in a sequential order and, hence, do not need custom execution policies, this lack of support becomes problematic for our GPU counterparts where aspects like controlling kernel synchronization play an important role. Add support for custom execution policies to all host functions of `mutex` running GPU kernels to allow greater control by the user.
Partially addresses https://github.com/stotko/stdgpu/issues/351
> mutex: Add support for custom execution policies

- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
- test/stdgpu/vector.inc
Whereas the containers operate in a sequential order and, hence, do not need custom execution policies, this lack of support becomes problematic for our GPU counterparts where aspects like controlling kernel synchronization play an important role. Add support for custom execution policies to all host functions of `vector` running GPU kernels to allow greater control by the user.
Partially addresses https://github.com/stotko/stdgpu/issues/351
> vector: Add support for custom execution policies

- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- test/stdgpu/deque.inc
Whereas the containers operate in a sequential order and, hence, do not need custom execution policies, this lack of support becomes problematic for our GPU counterparts where aspects like controlling kernel synchronization play an important role. Add support for custom execution policies to all host functions of `deque` running GPU kernels to allow greater control by the user.
Partially addresses https://github.com/stotko/stdgpu/issues/351
> deque: Add support for custom execution policies

- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- test/stdgpu/unordered_datastructure.inc
Whereas the containers operate in a sequential order and, hence, do not need custom execution policies, this lack of support becomes problematic for our GPU counterparts where aspects like controlling kernel synchronization play an important role. Add support for custom execution policies to all host functions of `unordered_map` and `unordered_set` running GPU kernels to allow greater control by the user.
Partially addresses https://github.com/stotko/stdgpu/issues/351
> unordered_map,unordered_set: Add support for custom execution policies

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/type_traits.h
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/memory.h
In order to safely skip calling `destroy` on trivial types, the `allocator_traits` class is also checked for specializations where the behavior of the `construct` and `destroy` functions could potentially be changed in an arbitrary and unpredictable way. As of C++23, such specializations have been forbidden. Thus, remove the check to reduce the maintenance burden.
> memory: Remove allocator_traits specialization detection

- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/deque.cuh
- src/stdgpu/execution.h
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/bitset_detail.cuh
- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/mutex_detail.cuh
- src/stdgpu/impl/type_traits.h
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/memory.h
- src/stdgpu/mutex.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- src/stdgpu/vector.cuh
- test/test_utils.h
All containers recently gained support for custom execution policies. However, a proper detection mechanism is still missing and also complicates proper overload resolution of member functions which may lead to confusing compilation errors. Add `is_execution_policy` traits to detect all policies defined by thrust and conditionally enable all policy-related member functions of the containers.
While this is a significant improvement, defining custom policies would now requires specializing `is_execution_policy` since the policy check does not properly detect them. However, only relying on the ones from thrust should be sufficient for now.
> execution: Add is_execution_policy trait and conditionally enable policy-based functions

- src/stdgpu/algorithm.h
- src/stdgpu/execution.h
- src/stdgpu/impl/algorithm_detail.h
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/numeric_detail.h
- src/stdgpu/memory.h
- src/stdgpu/numeric.h
While #377 improved the overload resolution situation with the containers, the same issue also applies to the free functions defined in `algorithm`, `memory`, and `numeric`. Conditionally enable the involved functions like in the case of the containers to closer adhere to the C++ standard.
> execution: Apply is_execution_policy to overload more algorithms conditionally

- src/stdgpu/CMakeLists.txt
- src/stdgpu/atomic.cuh
- src/stdgpu/bit.h
- src/stdgpu/cuda/atomic.cuh
- src/stdgpu/execution.h
- src/stdgpu/hip/atomic.h
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/type_traits.h
- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/memory.h
- src/stdgpu/openmp/atomic.h
- src/stdgpu/type_traits.h
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- src/stdgpu/vector.cuh
So far, `type_traits` only contained types and macros only intended for internal usage. With the addition of `remove_cvref`, it now contains a publicly facing API. Move it out from the internal implementation directory and add respective documentation for it.
> type_traits: Move to public module and add documentation

- src/stdgpu/impl/vector_detail.cuh
- test/stdgpu/deque.inc
- test/stdgpu/vector.inc
By default, `index_t` resolves to a 32-bit integer, which on the supported platforms resolves to `int`. While the complementary 64-bit mode, where it typically resolves to `long int` is also supported, the code is less frequently tested against a high warning level. Fix the conversion warnings that appeared after manual analysis and compilation in 64-bit index mode.
> src,test: Fix conversion warnings for 64-bit index_t

- test/stdgpu/unordered_datastructure.inc
In #380 several conversion warnings only appearing with 64-bit indexing enabled have been fixed. While this results in clean builds on Ubuntu again, there are a few remaining warnings on Windows left. Fix these warnings as well to ensure clean builds on all supported platforms.
> test: Fix more conversion warnings for 64-bit index_t

- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
Our CI currently tests for various platforms and configurations. Regarding the library options, the default 32-bit indexing is only tested while the optional 64-bit indexing is not considered so far. Add the respective CI jobs to test 64-bit indexing on Ubuntu and Windows. This will reduce the likelihood of regressions in the future.
> CI: Add jobs for 64-bit indexing

- src/stdgpu/functional.h
- src/stdgpu/impl/functional_detail.h
- src/stdgpu/impl/type_traits_detail.h
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- test/stdgpu/functional.cpp
The `hash` function object from `functional` is currently only defined for specializations and will result in a compile error otherwise. However, this compiler error is not very informative (see #374) and does not provide any hints about a missing specialization when used with custom types. Make `hash` always and disable all constructors for non-specialized types to follow the C++ standard more closely. Furthermore, improve the error messages in such cases by adding additional compile-time checks in `unordered_map` and `unordered_set`.
> functional: Make hash more SFINAE-friendly and improve error messages

- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- test/stdgpu/unordered_datastructure.inc
In comparison to `vector` and `deque`, the containers `unordered_map` and `unordered_set` only exhibit a const-version of the `device_range()` function. This does not allow for e.g. updating the mapped value in `unordered_map`. Add the respective non-const version to close this gap and enable these use cases.
> unordered_map,unordered_set: Add non-const device_range function

- src/stdgpu/impl/ranges_detail.h
With the recent addition of non-const `device_range()` functions for `unordered_map` and `unordered_set` in #385, a bug in the internal access of the respective indexed ranges has been exposed. While for the const versions, the created copy of the indexed constant value has the same semantics as a reference, this is no longer the case in the non-const version where the e.g. the mapped value of a pair should be updated. Fix this bug by properly returning a reference instead of a value to prevent the accidental copy.
> ranges: Fix access in indexed range

- benchmark/CMakeLists.txt
A new release of google benchmark is available. Pull in this new version to benefit from the major improvements and cleanups.
> benchmark: Upgrade google benchmark to 1.8.2

- test/stdgpu/CMakeLists.txt
The recommended way of linking against third-party dependencies in CMake is to use the respective namespaced target names which will will work for both imported targets as well as locally built, aliased targets. While this best practice is followed for the benchmark library, the gtest library is used without its namespace. Fix this minor inconsistency.
> cmake: Use gtest alias target in tests

- test/stdgpu/algorithm.cpp
When compiling with a recent version of CUDA, the `algorithm` test emits a warning that the half data type defined by some CUDA headers is shadowed by a local variable in that test. Fix this warning by renaming the respective variable.
> test: Fix shadow warning with half type

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- test/stdgpu/memory.inc
All containers currently rely on manual memory management via the `createDeviceObject` and `destroyDeviceObject` factory functions since the containers themselves are shallow-copyable to allow using them within device functions and, in turn, crossing the host-device memory boundaries. Ideally, the containers should manage their memory automatically and be deep-copyable. However, this transition involves a larger redesign of significant portions of the containers.
Introduce `device_unique_object` in the `memory` module as a lightweight resource wrapper around the current object creation API with similar semantics as `unique_ptr`. This allows for automatic memory management, including proper handling of the involved execution policies, and would involve only minimal effort to port existing …
> memory: Add device_unique_object resource wrapper

- README.md
- cmake/hip/determine_thrust_paths.cmake
- doc/stdgpu/index.md
- src/stdgpu/hip/CMakeLists.txt
- src/stdgpu/hip/impl/device.cpp
- src/stdgpu/hip/impl/memory.cpp
- test/stdgpu/hip/CMakeLists.txt
- test/stdgpu/hip/memory.hip
Although AMD's GPU support in terms of their ROCm/HIP framework is still lacking behind CUDA in various aspects, the situation seems to have improved in recent ROCm versions. Thus, streamline our HIP backend to closer match the CUDA backend. This reduces the differences between the backends and, in turn, slightly the maintenance burden.
Note that the HIP backend is still considered **experimental**.
> General: Streamline HIP backend

- docs/_static/stdgpu_custom_sphinx.css
- docs/conf.py
- docs/requirements.txt
- tools/dev/color_contrast.py
The dark mode of the Sphinx book theme has been modified since the port to Sphinx to reduce the excessively high contrast of the separator. and to make the background a bit brighter. To come up with better aligned colors, the contrast needs to be analyzed more thoroughly. Add a respective script for this purpose and define a better separator color while dropping the brighter background. Furthermore, prepare for using Sphinx Design and ensure consistency with these changes.
> docs: Use better aligned colors for dark mode

- docs/development/contributing.md
The contributing guide has been overhauled in #398 which also introduced a reference to the pitchfork layout convention. However, the link to this convention contains an ampersand symbol `&` which gets transformed to `&amp;` breaking the link. Fix this bug by using a HTML link instead of a Markdown link which preserves the ampersand.
> docs: Fix link to pitchfork layout convention

- README.md
- docs/development/contributing.md
- docs/development/contributing/documentation.md
- docs/development/contributing/tests.md
- docs/getting_started/building_from_source.md
- docs/getting_started/integrating_into_your_project.md
- docs/index.md
After introducing the reworked contributing guide, further parts of the documentation could be improved as well. Add a new overhauled Getting Started guide as a dedicated section into the documentation. This replaces the previous "Building" and "Integration" sections in the `README` and contains more detailed instructions in a cleaner layout.
Furthermore, the links in the contributing guide are also updated to point to this new guide.
> docs: Add overhauled Getting Started guide

- README.md
- docs/index.md
A good introduction in the `README` and documentation is crucial to get the library's goals, features, and design communicated to users. While our introduction mentions these points, it is a bit wordy and sometimes not easy to immediately grasp. Rewrite it by listing all important aspects briefly in a bullet list. Furthermore, remove redundant parts in the docs version, i.e. the docs main page, and make use of Sphinx design elements.
> docs: Rewrite introduction in README and documentation main page

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- tests/stdgpu/memory.inc
In #391, a new wrapper class for automatically managing device objects has been introduced. However, empty managed object can not be constructed which prohibits use cases where, e.g., such a managed object is moved. Add a respective constructor that accepts a `null_object` as well as an overload of `operator bool()` to enable testing for empty objects.
> memory: Add constructor for empty device_unique_object

- .github/workflows/analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/documentation.yml
- .github/workflows/style.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
New major releases for the used actions in our CI have been released. Update our jobs to use these and to prepare for an upcoming simplification of the jobs.
> CI: Update used actions

- README.md
In #404 the badges were updated. However, the link in the Lint badge is partially broken. Fix this issue and also drop the lower important coverity badge to have all badges on a single line.
> README: Fix link in badge

- CMakeLists.txt
- cmake/cmake_uninstall.cmake.in
CMake 3.28 has been recently released. Keep up with the pace of introduced behavioral changes by bumping the maximum supported policy version.
> cmake: Update support for CMake 3.28

- docs/api/object.md
- examples/createAndDestroyDeviceObject.cpp
- src/stdgpu/atomic.cuh
- src/stdgpu/bitset.cuh
- src/stdgpu/memory.h
- src/stdgpu/mutex.cuh
- src/stdgpu/queue.cuh
- src/stdgpu/stack.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- src/stdgpu/vector.cuh
- tests/stdgpu/memory.inc
The `create*` API returns the newly constructed and initialized object that can then be used. However, ignoring the return value will result in loosing access to that object and thus will lead not only to a likely crash but also to a memory leak. Add the `[[nodiscard]]` attribute to these functions to better warn users of this issue and indicate the correct usage of these functions.
> General: Add nodiscard attribute to create* API

- src/stdgpu/deque.cuh
In #409 the `[[nodiscard]]`  attribute has been added to the `create*` API. However, `deque` has been accidentally missed out. Also add the attribute for this class to fix this oversight.
> deque: Add nodiscard attribute to create* API

- .gitignore
This PR adds more IDE related folder to `.gitignore` folder
> add more ide related folder to gitignore

- src/stdgpu/impl/unordered_base_detail.cuh
The size of the internal excess list of `unordered_map` and `unordered_set` is determined by the expected amount of collisions, but at least 1. However, insertion as a precaution requires a non-empty excess list to proceed even if the inserted element will not produce a collision. In case of very small capacities, e.g. `n = 4`, this may result in insertion failures if a collision happens. Increase the excess count by 1 to account for this "reserved" element.
Closes #411
> unordered_map,unordered_set: Fix excess list size for very low capacities

- src/stdgpu/impl/unordered_base_detail.cuh
In #414, the excess list size computation has been fixed for very low capacities. However, the use of `std::max` is not needed anymore due to the fix. Remove this expression to simplify the computation of the size.
While at it, also make the estimate for the expected collisions slightly more conservative by always rounding up the computed value.
> unordered_map,unordered_set: Simplify excess list size computation

- docs/_static/extra_stylesheet.css
- docs/_static/stdgpu_custom_doxygen.css
- docs/_static/stdgpu_custom_sphinx.css
- docs/conf.py
- docs/requirements.txt
Recently, several of our dependencies for the documentation received some updates. While there seem to be some issues with the styling, it is still better to keep them up to date. Remove the restriction on the Sphinx Book Theme and add some workaround for the style issues.
The doxygen version is kept fixed for the time being as this requires some further testing as well as checking if e.g. doxysphinx is compatible.
> docs: Update dependencies and workaround further style issues

- cmake/Findthrust.cmake
- tools/backend/check_install_openmp.sh
- tools/backend/configure_openmp.sh
- tools/backend/configure_openmp_clang_tidy.sh
- tools/backend/configure_openmp_cppcheck.sh
- tools/backend/configure_openmp_documentation.sh
- tools/backend/configure_openmp_lcov.sh
- tools/dev/download_thrust.sh
Thrust has been merged together with libcudacxx and CUB into the [CUDA C++ Core Libraries (CCCL)](https://github.com/NVIDIA/cccl). Furthermore, thrust 2.X now requires libcudacxx, so our current way of detecting thrust may be incomplete. Extend `Findthrust.cmake` to account for this new scenario and upgrade the thrust version used in the CI to stay up to date.
Although CCCL 2.4.0 is the newest version, we employ 2.2.0 as there are some outstanding compiler issues with CUDA 12.4+ (which comes with such a more recent version).
> cmake,scripts: Improve thrust detection and upgrade used version in CI

- tests/CMakeLists.txt
A new release of googletest is available. Pull in this new version to benefit from the major improvements and cleanups.
> tests: Upgrade googletest to 1.14

- benchmarks/CMakeLists.txt
A new release of google benchmark is available. Pull in this new version to benefit from the major improvements and cleanups.
> benchmarks: Upgrade google benchmark to 1.8.4

- examples/cuda/unordered_map.cu
- examples/openmp/unordered_map.cpp
- src/stdgpu/impl/utility_detail.h
- src/stdgpu/utility.h
With thrust 2.3.0+ (bundled in CUDA 12.4+), their implementation of `pair` have been replaced by `cuda:std::pair` from libcudacxx. Unfortunately, this causes compiler errors due to ambiguous namespace resolution for overlapping functionality between stdgpu and libcudacxx. Replace the alias to thrust's `pair` class with a custom implementation to fix these issues.
This further reduces the dependency to thrust, see #279.
> utility: Add custom pair implementation

- CMakeLists.txt
CMake 3.30 has been recently released. Keep up with the pace of introduced behavioral changes by bumping the maximum supported policy version.
> cmake: Update support for CMake 3.30

- src/stdgpu/impl/iterator_detail.h
Affecting compilation issue mentioned here: https://github.com/stotko/stdgpu/issues/417#issuecomment-2286612930. The other device-code compilation errors with CUDA 12.5 mentioned in the issue are not adressed with this PR.
Thrust changed the namespace for its implementations from `thrust::` to `thrust::<<ABI_IDENTIFIER>>::` since thrust 2.3.0.
For the few template specializations in iterator_impl, its necessary to to use the correct namespaces. Using the `THRUST_NAMESPACE_BEGIN/END` marcos should make sure that we always use the correct namespace, even with older CUDA Toolkit versions, but I did not exhaustively test that.
> Fix thrust namespace for CUDA 12.6

- docs/getting_started/building_from_source.md
- src/stdgpu/CMakeLists.txt
- src/stdgpu/cuda/CMakeLists.txt
Fixing a compilation issue with thrust on CUDA 12.6 required leveraging a macro that was introduced in thrust 1.13.1 (and CUDA 11.5), see #428. Although we technically support version down to CUDA 11.0 (released March 2020), such an old version will very likely not be used as support for the current GPU generations (RTX 30XX and 40XX) was not present at that time. Thus, bump to the requirements to thrust 1.13.1 and CUDA 11.5 (released October 2021). This may also unblock some further cleanups in the future.
> General: Bump required thrust version to 1.13.1

- docs/conf.py
Previously, the `author` field was not used such that this information was provided in the `copyright` field. With the more recent versions of Sphinx and other related libraries, the `author` field became mandatory. Use it to avoid the default "Author not set" text.
> docs: Use author field for Sphinx

- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
Due to the recently bumped requirements for CUDA, the workaround for `to_address`  in `memory` to avoid a compiler warning is no longer needed. Drop this pre C++17 SFINAE version in favor of the simpler version leveraging constexpr syntax.
> memory: Drop workaround for to_address

- src/stdgpu/algorithm.h
- src/stdgpu/impl/algorithm_detail.h
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/numeric_detail.h
- src/stdgpu/memory.h
- src/stdgpu/numeric.h
The recently introduced custom `pair` implementation in #425 resulted in regressions when using thrust's algorithms that have also been implemented by us, e.g. `thrust::copy(...)`. This is caused by ADL since `pair` now is a member of the stdgpu namespace rather than thrust as before. Use ADL barriers to ensure that calling any algorithm from thrust will not accidentally delegate to our implementation.
Fixes #432
> algorithm,memory,numeric: Improve thrust compatibility via ADL barriers

- src/stdgpu/impl/utility_detail.h
There is a type in the implemetation of the templated version of custom pair's operator =
> fix custom pair implementation operator=

- src/stdgpu/impl/unordered_base_detail.cuh
- tests/stdgpu/unordered_datastructure.inc
The excess size of `unordered_map` and `unordered_set` have been estimated based on the birthday paradox and then conservatively lowered as some amount of estimated collisions also includes entries sitting in a bucket instead of the excess list. This size adjustment has been performed to save memory. However, the underlying assumption of this estimate is a perfect uniform distribution of the hashes which is the best case scenario. With common hash functions, that distribution may be worse leading to a larger amount of required excess entries, especially at high load factors. Use the estimated number directly as it overestimates the excess list size by a factor close to 2 (about 90% collisions will typically be between exactly 2 entries). This has been tested to work better with high load …
> unordered_map,unordered_set: Increase excess size

- cmake/setup_clang_format.cmake
After adopting the pitchfork layout in #394, the search directories used to collect all files applicable for clang-format were not updated. Thus, the formatting script as well as the accompanying check script missed half of the project since then. Fix this issue and also include helper files.
> Fix search directories for clang-format

- cmake/setup_cppcheck.cmake
- src/stdgpu/impl/memory_detail.h
- tests/stdgpu/algorithm.cpp
- tests/stdgpu/atomic.inc
- tests/stdgpu/functional.cpp
- tests/stdgpu/memory.inc
Recent versions of cppcheck have added more diagnostics to detect potential issues. Fix these issues to prepare for CI upgrade.
> src,test: Fix more cppcheck warnings

- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
The CI image for Ubuntu 24.04 has been released a few months ago and has matured until now. Upgrade most jobs to this version and drop the old Ubuntu 20.04.
> CI: Upgrade to Ubuntu 24.04 image

- .clang-format
- .github/workflows/lint.yml
- benchmarks/stdgpu/unordered_datastructure.inc
- cmake/FindClangFormat.cmake
- cmake/setup_clang_format.cmake
- src/stdgpu/bitset.cuh
- src/stdgpu/impl/functional_detail.h
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/impl/type_traits_detail.h
- src/stdgpu/memory.h
- tools/ubuntu/install_clang_format.sh
Since the introduction of `clang-format`  in #275, some time has passed and recent versions have refined and added further options to styling. Upgrade the style to version **18** which comes with Ubuntu 24.04 and will be kept for the next few years.
> General: Upgrade to clang-format 18 style

- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/cuda/memory.h
- src/stdgpu/hip/impl/memory.cpp
- src/stdgpu/hip/memory.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/openmp/impl/memory.cpp
- src/stdgpu/openmp/memory.h
The backend implementation of `memory` used the term "dispatch" to indicate that the backend is performing the operation based on the passed memory type. However, this just makes the names more complex. Furthermore, auxiliary functions for actually calling the backend implementation are defined as well which, however, are never exposed outside and just add another layer of indirection. Simplify the name and call convention to reduce bloat and prepare the backends for future feature additions.
> memory: Simplify names of backend functions

- src/stdgpu/atomic.cuh
- src/stdgpu/impl/atomic_detail.cuh
- tests/stdgpu/atomic.inc
The upcoming C++26 standard will introduce `fetch_min` and `fetch_max`  functions in the `atomic` module. We already expose them for `atomic` and `atomic_ref`  but lack the respective non-member functions. Add an implementation of these and update he signature of the remaining ones to more closely match the C++ standard.
> atomic: Add non-member functions for fetch_min and fetch_max

- benchmarks/stdgpu/main.cpp
- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/cuda/memory.h
- src/stdgpu/hip/impl/memory.cpp
- src/stdgpu/hip/memory.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/memory.h
- src/stdgpu/openmp/impl/memory.cpp
- src/stdgpu/openmp/memory.h
- tests/stdgpu/main.cpp
- tests/stdgpu/memory.inc
Managed memory has always been a niche feature in the `memory` module and required more complex initialization code including additional workarounds to ensure correct behavior on older GPUs. Other frameworks like PyTorch also do not support it for similar reasons. Thus, drop the support for managed memory. This will facilitate future improvements such as more complete stream/execution policy support.
> memory: Drop support for managed memory

- src/stdgpu/cuda/impl/error.h
- src/stdgpu/cuda/impl/memory.cpp
- src/stdgpu/cuda/memory.h
- src/stdgpu/hip/impl/error.h
- src/stdgpu/hip/impl/memory.cpp
- src/stdgpu/hip/memory.h
- src/stdgpu/impl/memory.cpp
- src/stdgpu/openmp/impl/memory.cpp
- src/stdgpu/openmp/memory.h
The backend interface of `memory` expects the dynamic memory type to dispatch to the correct platform-specific call. However, this introduces a cyclic dependency to the high-level `memory` interface. Furthermore, dispatching should not be part of the backend logic as the backends should only provide the implementations of small building blocks which, in turn, are used to build the entire business logic. Redesign the backend API by splitting the malloc/free/memcpy functions into low-level pieces tied to a specific memory type configuration and move the respective dispatching logic up to the high-level shared implementation.
> memory: Make backend interface more low level

- benchmarks/stdgpu/main.cpp
- src/stdgpu/atomic.cuh
- src/stdgpu/cuda/CMakeLists.txt
- src/stdgpu/cuda/impl/memory_detail.h
- src/stdgpu/cuda/memory.h
- src/stdgpu/hip/CMakeLists.txt
- src/stdgpu/hip/impl/memory_detail.h
- src/stdgpu/hip/memory.h
- src/stdgpu/impl/atomic_detail.cuh
- src/stdgpu/impl/memory_detail.h
- src/stdgpu/openmp/CMakeLists.txt
- src/stdgpu/openmp/impl/memory_detail.h
- src/stdgpu/openmp/memory.h
- tests/stdgpu/atomic.inc
- tests/stdgpu/main.cpp
The load/store functions in `atomic` still use the legacy API for copying memory between host and device which, in turn, is fully synchronous. Although all containers received support for custom `execution_poliy`s, this support is complete due to the aforementioned limitation. Extend the support for `atomic` to address this issue.
> atomic: Extend support for custom execution policies

- src/stdgpu/deque.cuh
- src/stdgpu/impl/deque_detail.cuh
- tests/stdgpu/deque.inc
Although all containers received support for custom `execution_policy`s, this support is complete due to a left-over synchronous memcpy. Fortunately, this limitation has been resolved. Extend the support for `deque` accordingly to fill some of the remaining holes.
> deque: Extend support for custom execution policies

- src/stdgpu/impl/deque_detail.cuh
- src/stdgpu/impl/vector_detail.cuh
- src/stdgpu/vector.cuh
- tests/stdgpu/vector.inc
Although all containers received support for custom `execution_policy`s, this support is complete due to a left-over synchronous memcpy. Fortunately, this limitation has been resolved. Extend the support for `vector` accordingly to fill some of the remaining holes.
> vector: Extend support for custom execution policies

- .github/workflows/coverage.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
Version 5.0.4 which has been released yesterday updated its internal wrapper code which, however, introduced a regression and prevents reports from being displayed. The reason seems that the git commits get messed up but we cannot do much on our side to fix this. Fall back to a slightly older version to workaround this issue until it has been fixed upstream.
> CI: Fall back to older codecov version

- src/stdgpu/impl/unordered_base.cuh
- src/stdgpu/impl/unordered_base_detail.cuh
- src/stdgpu/impl/unordered_map_detail.cuh
- src/stdgpu/impl/unordered_set_detail.cuh
- src/stdgpu/unordered_map.cuh
- src/stdgpu/unordered_set.cuh
- tests/stdgpu/unordered_datastructure.inc
Although all containers received support for custom `execution_policy`s, this support is complete due to a left-over synchronous memcpy. Fortunately, this limitation has been resolved. Extend the support for `unordered_map` and `unordered_set` accordingly to fill some of the remaining holes.
> unordered_map,unordered_set: Extend support for custom execution policies

- .github/workflows/coverage.yml
According to the triggered auto-update by dependabot in #452, a more recent point release of the codecov action seems to have fixed the regression that prevented reports from being displayed. Thus, revert the workaround from #451.
Supersedes #452
> CI: Allow for recent v5 versions of codecov action

- tests/stdgpu/iterator.cpp
The tests implicitly assume that int and size_t have different bit sizes,
which is not necessarily true, e.g. on 32 bit architectures.
> Force actual wrong alignment in wrong alignment tests

- src/stdgpu/limits.h
Instead of special-casing or assuming a particular signedness, you can
use the boolean expression ((T)(-1) < 0) to determine signedness of an
integer type at compile time.
> Let the compiler determine char signedness

- tests/CMakeLists.txt
A new release of googletest is available. Pull in this new version to benefit from the major improvements and cleanups.
> tests: Upgrade googletest to 1.16

- .github/workflows/tests.yml
The CI image for Windows 2025 has been released a few months ago and has matured until now. Since Windows 2019 will soon be retired (see [announcement](https://github.blog/changelog/2025-04-15-upcoming-breaking-changes-and-releases-for-github-actions/)), upgrade the respective jobs to this version.
> CI: Upgrade to Windows 2025 image
